### ISSUE TITLE
18RoyalGorge checklist

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#10110]
## Known Bugs

- [x] auto-routing after adding engineer/coal cubes doesn't work, it finds a route for the unmodified train

## UI Enhancements needed

Functionally there, but not so much visually

- [x] VGC gold cube slots / phase limitations
- [x] CF&I and VGC descriptions on card (probably best through abilities)
- [x] during track and dividend steps (when `choices` are available), don't render irrelevant private companies as if they have usable abilities
- [x] "used" cities during routing should show towns after the plus, except for 6-trains

## Config

These should be taken care of with `map.rb` and `entities.rb`, no special code needed

- [x] incremental cap, float on 20%
- [x] towns don't count as stops
- [x] 6x2 trains do count towns as stops, but double total
- [x] phase changes on different trains than usual

## Initial Auction
- [x] 5 privates - 2 yellow, 2 green, 1 brown
- [x] auctioned one at a time, yellow to brown
- [x] priority deal to most cash left (don't reorder players)

## Yellow Privates
- [x] Y1 St Cloud Hotel - +$20 revenue in Silvercliffe; moves to Canon City in brown
- [x] Y2 Ghost Town Tour Co - after last Gold is shipped from a hex, add a +$10 ghost town
- [x] Y3 Coal Creek Mines - owning corp gets a coal cube from the coal mine card (supply of 12) when anyone runs through Coal Creek
- [x] Y4 William Palmer - 10% share of Rio Grande and 10% share of Steel Mill
- [x] Y5 Territorial Prison - 1/2 price to build over terrain
- [x] Y6 Local Jeweler - $5 from bank when Gold is shipped, moves to owner's cash at start of SR

## Green Privates
- [x] G1 Doc Holliday - see treaty of boston; closes when debt is paid
- [x] G2 13 lb Gold Nugget - 1x ship 1 Gold for +$130 revenue instead of +$50
- [x] G3 Hanging Bridge Lease - may run route through royal gorge if 10% dividend paid to rio grande, from the corporation's cash or its president's cash
- [x] G4 Florence Oil Fields - no revenue in yellow
- [x] G5 Metals Investor - discount on steel/gold shares; if used, cannot sell the bought shares till next SR
- [x] G6 Coal Depot - 1 coal cube per $10 paid (round down) during auction

## Brown Privates
- [x] B1 Silver Mines - revenue only in brown
- [x] B2 Sulphur Springs - owning corp can close to turn Sulphur Springs into a city; if owned by a player in brown, pays $50 per OR if rail to sulphur springs exists
- [x] B3 Steel Depot - owning corp may use 0-2 steel from card to lay yellow track for free; not additional actions
- [x] B4 Gold Miner - virtual 20% share of VGC, doesn't count against cert limit, closes on first 5+
- [x] B5 Track Engineer - each OR, choose one train to extend by one city
- [x] B6 US Mint Worker - close to buy 1-2 gold shares at 50% discount

## Corporations
- [x] Corporations available to float depend on their year established
- [x] 2 corps available in yellow, 2 more in green, 1 more in brown
- [x] Gold and Steel don't have presidents, only pay out and change stock price at end of OR set; don't drop their price when sold
- [x] if Florence or New Orleans railroads are in the game, their home station is now a city

## Operating Round
- [x] CF&I starts with $50 in its dividend pool
- [x] 6 track actions
- [x] pay for steel from CF&I
- [x] add choice to pick column for each color of tile placed
    - [x] add choice to pick a more expensive cube from the column (boost up steel dividends and/or save money for a future company)
- [x] CF&I dividends
- [x] display available steel on table as shown on board
- [x] add choice step for picking a Gold to ship for +$50 on run
    - [x] gold placed on VGC track
- [x] 3-hex Royal Gorge tile (look at 18MEX's Mexico City for this)
- [x] Coal Cubes - 1 or 2 can be added to a train to extend the run (Y3, G6)
- [x] triple jumps for triple dividends
- [x] train limit not applicable if train will be rusted

## Treaty of Boston
- [x] Santa Fe is indebted to Doc Holliday x2
- [x] Rio Grande is indebted to Santa Fe x4
- [x] green royal gorge tile is laid, rio grande gets tokens there

## Debt
- [x] stock marker
- [x] debt can be paid off at any time during OR turn
- [x] increase debt at end of OR set
- [x] drop share price at end of game

## Game End
- [x] red section of stock market - after next set of ORs
- [x] first 6 train is purchased - after next set of ORs
- [x] bankruptcy - ends immediately

## Steel and Gold
- [x] "president" holding the only share needs to be allowed to sell it

**Comment by michaeljb** [comment]
why are companies rendering like they have `choices` during the dividend step? probably related to the shipping gold choice

**Comment by michaeljb** [comment]
after auction, priority deal to player with most cash, don't rearrange all seating
