### ISSUE TITLE
1832 implementation checklist

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#10122]
Setup
- [x] Currency format - $xxx
- [x] Bank - $12,000
- [x] Starting cash -  2 => 1050, 3 => 700, 4 => 525, 5 => 420, 6 => 350, 7 => 300 
- [x] Certificate limit 
- [x] Meta
- [x] Map
  - [x] Show future tile upgrades for Charleston and Jacksonville (Y)
  - [x] Indicate Boomtown hexes
- [x] Tiles
  - [x] Label tile 611 as Y to simplify its reservation for Charleston and Jacksonville.
- [x] Corporation logos and colors

Private Companies
- [x] Sold for half to 2x value in phases 3-4
- [x] West Virginia Coal fields can be bought for half to face in Phase 2.
- [x] P1 - Carolina Stagecoach Company
  - [x] Value - $20, Revenue $5
- [ ] P2 - Cotton Warehouse
  - [x] Value - $40, Revenue $10
  - [x] Adds $10 to the value of one non-costal city for the owning corp
  - [ ] Must be able to assign it to a specific city in the case of Atlanta, which has 3 separate cities on it.
- [ ] P3 - Atlantic Shipping
  - [x] Value - $50,  Revenue 10
  - [x] Can be placed on any revenue hex with a Port symbol
  - [x] Increases value of stop by $20 for the owning corp
  - [x] increases value of stop by $10 for all other corps
- [ ]  P4 - London Investment
  - [x] Value - $70, Revenue $10
  - [x] cannot be bought in
  - [ ] Can be traded for a 10% IPO share of any corp
  - [x] Can only be exchanged during an SR
  - [ ] Corp must have been parred in the current SR (Including Central of Georgia Railway in SR1)
  - [ ] This counts as your purchase action
  - [ ] Continues to pay revenue until the corp pays its first dividend.
- [ ] P5 - West Virginia Coalfields
  - [x] Value - Value - $80, Revenue - $15
  - [x] Blocks hexes around WVCF hex until bought in by corp or closed. 
  - [x] owning corp receives a free coal token
  - [x] once bought in, other corps can buy a coal token from this corp, $40 to corp, $40 to bank
  - [ ] this token allows a corp to run to and through the WVCF hex
  - [ ] Corp must have a route to WVCF to buy token
  - [ ] buying WVCF token counts as a yellow tile lay
- [ ] P6 - Southern Bank
  - [ ] Variant rule only. May not initially implement. 
- [x] P7 - Central Railroad & Canal
  - [x] Value - $200, revenue - $30
  - [x] Cannot be bought by a corporation
  - [x] Comes with the president's share of Central Of Georgia Railway
  - [x] Closes when CG buys its first train

Corporations
- [ ] Major corporations
  - [x] Corps don't pay terrain costs for their home hex. 
  - [ ] FECR
    - [ ] Can lay a special token in Miami (N16) for $100 that adds $50 to its runs there.

Systems
- [x] 5 Systems in the game
- [ ] can't be started like a normal corp, only via merger
- [ ] has two shells, each with the normal corp train limit (like in 1828)
- [ ] Only required to own one train between the two shells (like in 1828)
- [ ] can choose to EMF a train into an empty shell (like in 1828)
- [ ] can move trains between shells at any time to force an EMF (unlike 1828)
- [ ] cannot sell shares to fund a train if it has at least one train in its shed (unlike 1828)

Trains
- [x] uses 1870 trains, with a modified count

ISR
- [x] Standard waterfall

Stock Round
- [x] Identical to 1850 _except_:
  - [ ] a System may redeem up to two 5% shares per SR, _one per turn_.

Operating Round
- [x] Track
  - [x] two yellow or one upgrade
  - [x] systems can lay an additional yellow (3 yellow or one yellow one upgrade)
  - [x] systems can't upgrade the tile just laid
- [ ] Miami (N16) pays 0 the first time a corp runs to it before Phase 5
- [x] Boomtown hexes 
  - [ ] Boomtown hexes initially take yellow towns with a boomtown token. 
  - [ ] Yellow Boomtowns can upgrade either to a regular yellow city, or to a green town. 
- [ ] West Virginia Coal Fields
  - [x] cannot lay track into West Virginia Coal Fields (B14) until P5 is closed or owned by a corp
  - [ ] buying a Coal token uses up a yellow tile lay
  - [x] cannot trace a route to or through B14 unless corp owns a Coal token
- [x] Dividends
  - [x] Identical to 1870/1850
- [x] Train buying
  - [x] identical to 1870 except in the case of systems (see Systems section)
- [x] EMR
  - [x] for the most part identical to 1870 except in the case of systems (see Systems section)

Merger Rounds
- [ ] MR occurs after each SR in Phases 4 & 5
- [ ] one last one immediately after the purchase of the first 6-train
- [ ] players act in priority order during this phase
- [ ] two types of action: system merger and takeover
- [ ] each corp may take part in at most one system merger, and one takeover.
- [ ] all mergers and takeovers require consent from the other president (if applicable).
  - [ ] in the final merger round, corps must have the same president to merge
- [ ] Corps must be connected to merge/takeover
- [ ] Both corps must have already operated to merge/takeover
- [ ] **Systems**
  - [ ] all shares are exchanged 1:1 for the new 5% system shares
  - [ ] all assets are merged
  - [ ] all tokens are converted into the new system's tokens. All unused tokens are $100 tokens.
  - [ ] any city with two tokens from the new system returns one to the system's charter. This will be a $100 token.
  - [ ] If the new system has two coal tokens, one is returned to the bank with no compensation.
  - [ ] player with the most shares gets the 4-share 20% president's cert. 
  - [ ] if multiple players have an equal amount, the president is the first of those players in priority order, starting from the merge initiator.
  - [ ] if either (or both) of the president shares for the merging corps were not held by the president of the newly formed system, those president certs become 2-share 10% certs. 
  - [ ] new share price is average of the two corps' share value, rounded up or down to the nearest value on the market. If exactly halfway between, round up. 
  - [ ] To establish the exact position of the System's token on the stock market, place it in the new price share value box on the same row as the leftmost predecessor company's token, and then move it down and to the right along the diagonal until it hits either the soft ledge or the hard ledge, whichever comes first.
  - [ ] Max new share price is $275
- [ ] **Takeovers**
  - [ ] One corp/system buys out another corp/system.
  - [ ] Surviving corp remains a 10-share corp
  - [ ] Surviving corp retains all assets of the other corp (money, trains, treasury shares, and companies.
  - [ ] any unused tokens from the acquired corp are lost. 
  - [ ] existing tokens are converted to the buying corp's label
  - [ ] any city with two tokens from the new system returns one to the system's charter. This will be a $100 token.
  - [ ] If the new system has two coal tokens, one is returned to the bank with no compensation.
  - [ ] Shares owned by players and shares in the open market are purchased at current market value. Unsold shares are purchased at their par value. Treasury shares are not paid for, as they are considered an asset.
  - [ ] The buying corp buys shares with cash. If the corp doesn't have enough cash, the president must contribute cash to complete the merger. To do so, he may sell stock (not including stock in the company being purchased) subject to the 50% maximum in the open market. A player may not go bankrupt in this manner - if he is not able to raise sufficient cash, the merger is not allowed.
  - [ ] certificate limit is adjusted
  - [ ] discard trains down to train limit - president's choice

Game End
- [x] Bank runs out of money
  - [x] Play until end of OR set
- [x] player bankruptcy
  - [x] game ends immediately

Variants (may not implement initially, especially The Civil War)
- [ ] game ends the OR where a corp/system reaches $400 on the stock market
- [ ] 1830 trains - discard 8, 10, and 12 trains, use unlimited diesel trains with a $300 trade in for 4, 5, and 6 trains.
- [ ] The Southern Bank (Private company P6)
- [ ] Historical Order Start - corps open in a specific order, may not float a new corp until all previous corps have floated, thou you may buy shares in subsequent corps so long as it doesn't float them.
- [ ] The Civil War (not extensively tested)
  - [ ] on the purchase of the first 4-train:
    - [x] All 2-trains are rusted as usual
    - [ ] flip a coin - remove all even/odd numbered yellow tiles if the coin comes up heads/tails
    - [ ] All green tiles are downgraded to the yellow tile they were upgraded from
    - [ ] train limit is 1 for the rest of the game
    - [ ] all corps and players pay half their cash (rounded down) to the bank
    - [ ] All corp share values move 3 spaces to the left, or down if they can't move any further left.
- [ ] No mergers.
