### ISSUE TITLE
[1854] Checklist

### ISSUE THREAD

**Issue by andrewzwicky** [tobymao/18xx#10399]
**Setup**

- [ ] Set up the Austria map, the Local map, and the Shares' board.
- [ ] The 2 trains and the 1+ are available for purchase immediately and are laid out besidethe map. The remaining train cards are sorted by range and put beside the available train cards (lowest range on top). Make two stacks – one for the regular trains, one for the Plus trains. When the available trains are sold, lay out the next type.
- [ ] Choose a player to be banker. The bank contains 10,000 Austrian Guilders (abbreviated to “G”). Depending on the number of players, the Starting Money per player is
    3 players: 860 G
    4 players: 650 G
    5 players: 525 G
    6 players: 450 G
- [ ] Place the Share Certificates in the spaces provided on the Game board for shares, with the Director’s certificate on the top of each stack. At the start of the game, the 40% Director’s share and three 20% shares are available.
- [ ] Put the other shares aside; they are only available after a Share Split.
- [ ] Place the track tiles next to the board. Only the yellow tiles are needed at first, but the others are relevant to planning for the later stages of the game.
- [ ] Lay out the certificates of the Private and Local Companies in this order: Außerfernbahn – Murtalbahn – Graz-Köflacher-Bahn – Mariazellerbahn (1) – Kernhofer Bahn (2) – Ybbstalbahn (3) – Steyrtalbahn (4) – Pyhrnbahn (5) – Salzkammergutbahn (6) – Arlbergbahn – Semmeringbahn.

**Mountain Railways (Privates)**

- [x] Mountain Railways are one-share private companies that pay a fixed income paid to the owner at the beginning of each Operating Round by the bank.
- [x] Private Railway companies neither lay track nor own and operate trains.
- [x] Their certificates count against the Share Limit.
- [ ] Any Major Company can use the special property of a Mountain Railway company owned by the Director of the company. They may also lay track free of charge on the hex the Mountain Railway is located. (Other Major Companies have to pay the cost indicated to build track there.)
- [ ] At the latest, all Mountain Railways will close when the first 5-train is bought (the last two will usually have been closed earlier). The extra properties which they confer on companies cease when the Mountain Railways close.
- [ ] In particular, the ``+10’’ marker on Graz, which gives the owning company a higher income, is taken from the board and loses its effect.

| Name | Cost | Income | Special properties |
| ----------- | ----------- |----------- |----------- |
| Außerfernbahn | 20 G |5 G | Building on one mountain is 20 G cheaper. |
| Murtalbahn | 50 G |10 G |Building one tunnel is 40 G cheaper. |
| Graz-Köflacher Bahn | 70 G |15 G |Routes through Graz earn 10 G extra. |
| Arlbergbahn | 170 G |20 G |Receives a 20% VB share. Closes when the VB runs for the first time. |
| Semmeringbahn| 190 G |25 G |Receives a 20% SD share. Closes when the SD runs for the first time |
