### ISSUE TITLE
22Mars checklist

### ISSUE THREAD

**Issue by vandamm** [tobymao/18xx#11021]
# 22Mars

- [ ] Game end 8 sets of SR-OR-OR
- [ ] Game end market (end of current OR)

### Game setup
- [ ] Random location of map boards
- [ ] Random rotation of map boards
- [ ] Deal random permit to each player
- [ ] Assign random permit to each corporation
- [ ] Assign random Revolt! Cards to remaining corporations
- [ ] [!] Each player can choose to keep the Permit card and pay for it or discard it
- [ ] Assign Priority cards randomly (public info)

### Market
- [ ] Buy two shares in red
- [ ] No IPO price, always market
- [ ] Close corp box
- [ ] Arrows on the market
- [ ] Move right 2x if payout 2xPrice
- [ ] End of SR - go up if fully owned

### Permits & Revolt! cards
- [ ] Give passive income
- [ ] Permits are removed when Revolt happens
- [ ] Unstarted corps don’t get permit income
- [ ] Some Permits have revolt that move marker on Revolt track
- [ ] Revolt card actions can only be used after revolt breaks out
- [ ] When player floats a corp, its permit is given to the player, and not attached to the corp

### Corporations
- [ ] 5 x 20% shares (president share is 20% too)
- [ ] 20% to float
- [ ] May own 100% (but will pay taxes)
- [ ] Home token placed on float
- [ ] Corp has 3 tokens: M, T, C
- [ ] C token moves Revolt by +1 when placed

### Priority auction round
- [ ] Before each SR
- [ ] Hidden bids
- [ ] After revealing, bid amount is added to the value of Priority card (1 to 5)
- [ ] After the bids determine new player order
- [ ] Higher Priority cards win ties
- [ ] Redistribute Priority cards (1st gets card 1, 5th gets card 5)

## Stock Round
- [ ] First turn for everyone is paying taxes
- [ ] Taxes paid if owning 3-4-5 shares in same company (10-20-30 credits)
- [ ] EMR if cannot pay taxes
- [ ] Sell/Buy
- [ ] Cannot sell CEO share
- [ ] Does limit change when bankrupt? [?]

### Operating Round
- [ ] Order: 1. Issue any number of shares OR redeem one share, 2. Buy trains, 3. Build track, 4. Run trains, 5. Place token
- [ ] When issuing shares, corp gets money by CMV, then move down 1 row per share issued
- [ ] Lay or upgrade 1 tile
- [ ] During upgrade can choose to reduce number of city slots from 3 to 2 if a slot is empty
- [ ] Black tile: only after Revolt happened 
- [ ] Black tile: can be placed on any non CC city hex, regardless of its color
- [ ] Black tile: 30c if no token, 70/50/30c if has token in green/yellow/red slot
- [ ] All outside connections have a 10c town
- [ ] If a train is bought from another corp that already used it, it cannot be used this OR
- [ ] M (Miners) and T (Tourists) tokens add +10 to tile value (for any corp running to this tile)
- [ ] C (Convicts) token increase value of tile by +20
- [ ] After token is placed on a city, all future tokens in this city cluster (not tile) MUST be of same type (M/T/C)
- [ ] Home tokens don’t have type
- [ ] 7-train runs 6 stops, but doubles start OR end location
- [ ] 8-train runs 6 stops, but doubles start AND end location

EMR
- [ ] For train or for taxes
- [ ] EMR: first issue (if for train), then president
- [ ] CANNOT dump during EMR for train
- [ ] CAN dump during EMR for taxes
- [ ] Bankruptcy if unsuccessful EMR
- [ ] Corporations close if CEO bankrupted
- [ ] Tokens of closed corps remain on the board

Revolt track
- [ ] Displayed under the market on Info tab
- [ ] 4 green and 1 red cube are added to revolt bag
- [ ] Position 12 definitely causes a Revolt
- [ ] When moved to position 8-9-10-11, draw a cube from revolt bag. If red, revolt happenes.  Don’t return cube to the bag if green, so possibility increases 20/25/33/50/100%
- [ ] Bold game message when revolt track is moved

Revolt event
- [ ] Disable/discard all Permits
- [ ] Transform all C tokens on the board to neutral Revolt tokens
- [ ] Any cluster with Revolt token generates no revenue
- [ ] Revolt tokens block route connectivity, token placement and tile upgrades
- [ ] No new C tokens can be placed
- [ ] Revolt card abilities can now be used
- [ ] Black tile can be built after Black phase was triggered
- [ ] Immediately end current OR
- [ ] Play additional OR, then SR, then OR (they don’t count against game length)
- [ ] After that play normal next numbered OR
- [ ] If a corp has only home token placed (no M/T) and that cluster has a C token, it will be blocked after Revolt
- [ ] Such corp skips its OR turns until a C token is removed using Revolt card
- [ ] Such corp will have its stock token moved left after its each skipped turn

Permit cards
- [ ] Mining Area Alpha
- [ ] Mining Area Gamma
- [ ] Android Amusement Park
- [ ] Labor transports
- [ ] Paradise City
- [ ] Robot Factory
- [ ] Government Decision
- [ ] Infrastructure Push
- [ ] Prototype Hyperdrive

Revolt cards
- [ ] VIP Evacuation Plan
- [ ] Stopped Riot
- [ ] Tourist Evacuation
- [ ] Special Force Operation

**Comment by vandamm** [comment]
Bugs:
- [ ] When player has 50c and clicks on unstarted corporation, words "Par Price:" appear, but with no buttons
