### ISSUE TITLE
[1826] Implementation Checklist

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#11105]
**General**
- [x] Bank size: 12,000
- [x] Currency format: `F%s`
- [x] semi-restrictive tile lays
- [x] Starting capital: `{ 2: 900, 3:600, 4: 450, 5: 360, 6: 300 }
- [x] Cert limit: {2 => 28, 3 => 20, 4 => 16, 5 => 13, 6 => 11}
- [x] Player count: 2 - 6
- [ ] Train roster
- [x] Tile roster

**Phases**
- [x] 2H
  - [x] 1 OR
  - [x] Yellow
  - [x] Train limit: 2/4/-
  - [x] No cross-buy trains
  - [x] first offboard price
- [x] 4H
  - [x] 2 ORs
  - [x] Yellow, Green
  - [x] Train limit: 2/4/-
  - [x] No cross-buy trains
  - [x] first offboard price 
- [ ] 6H
  - [x] 2 ORs
  - [x] Yellow, Green
  - [x]  Train limit 1/3/-
  - [x] 2H rusts
  - [x] May cross-buy trains
  - [ ] Etat Corporation may form
  - [x] first offboard price 
- [ ] 10H
  - [x] 3 ORs
  - [x] Yellow, Green, Brown
  - [x] Train limit -/2/3
  - [x] 4H rusts
  - [ ] Privates close
  - [ ] SNCF Corporation may form
  - [ ] second offboard price 
- [ ] E
  - [x] 3 ORs
  - [x] Yellow, Green, Brown
  - [x] Train limit -/2/3
  - [x] 6H rusts
  - [ ] Special power tokens removed
  - [ ] SNCF Corporation may form
  - [x] third offboard price 
- [ ] TGV
  - [x] 3 ORs
  - [x] Yellow, Green, Brown, Gray
  - [x] Train limit -/2/3
  - [x] fourth offboard price

**Private Companies**
![image](https://github.com/user-attachments/assets/8ca6aecb-4cba-47bd-b286-ef18250d86d0)

**Events**
- [ ] 2H - Private abilities may be used
- [ ] 6H - Can cross-buy trains, Etat may form
- [ ] 10H - Privates close, SNCF may form
- [ ] E - Special power tokens removed, SNCF may form

**Stock Market**
- [x] white zone (as 1830)
- [x] yellow zone (as 1830)
- [x] red par prices: 110, 100, 90, 82, 75
- [ ] Stock Movement
  - [x] down one space per share sold or issued.
  - [ ] 10 share corps (not 5) move up if all shares are held by players (not treasury), no movement if at top.
  - [x] left if no dividend is paid.
  - [ ] right if corp pays out (full or half) an amount equal to or greater than share price, moves right once.
  - [ ] no movement if payout is greater than zero but less than share price.
  - [ ] left per loan taken.
  - [ ] right per loan paid.

**Trains**
![image](https://github.com/user-attachments/assets/343b0ddb-5430-4ee3-966c-ab815765d314)

- [x] 6H rusts 2H
- [x] 10H rusts 4H
- [ ] Quantity of 10H trains is dynamically determined based on # of corps in play after SCNF has opportunity to form. Since this happens on sale of first 10H, i think the easiest way will be to export unneeded 10H at that point. Corps/# of trains: 10/5, 9/4, 8/3, 7(or fewer)/2
- [x] E rusts 6H
- [x] E-trains do not include towns in revenue
- [ ] E-trains run for variable value:
  - [ ] When first is bought, it runs 2 cities and doubles them
  - [ ] When second & third are bought, they all run 3 cities and double them
  - [ ] when 4th is bought, they run 4 cities and double them.
  - [ ] When the first TGV is bought, all E trains now run 5 cities and **do not** double them.
- [ ] TGV
  - [x] TGV do not include towns in revenue
  - [ ] TGV may reuse track used by other trains
  - [x] TGV runs 3 cities and doubles their value
  - [ ] Max one TGV per corp

**Corporations**
- [ ] 50% float, incremental cap.
- [ ] Phase 2H: Can only start 5-share companies except for Etat Belge
- [ ] Phase 6H: Can only start 10-share companies, unsold shares in treasury.
- [ ] Phase 10H: Can only start 10-share companies, after 5 shares are sold, remaining shares are issued to the bankpool and corp receives full 10-share capitalization.
![image](https://github.com/user-attachments/assets/4fd526be-4c71-4d37-bd73-bdb6f147f37c)

**Destinations**
- [ ] Destination determination ignores tokens
- [ ] 5-share corp may choose to become 10-share during its OR, upon reaching destination.
- [ ] Upon conversion, remaining 5 shares added to treasury.
- [ ] 10-share corps do not have any destination benefit. 
- [ ] On Phase 10H, corps are all considered to have reached their destination immediately.

**Initial Auction**
- [x] Waterfall auction
- [x] if all pass, player with Priority buys P1, or all owned privates pay out.
- [x] Minimum bid 5 above face
- [x] Increments of 5
- [ ] only highest bid cash is reserved on each auction. (will need to look into this more)

**Stock Round**
- [ ] Sell / Buy
- [ ] price drops per share sold
- [ ] Parring
  - [ ] Incremental cap if parred before phase 10H, unsold incremental shares in treasury
  - [ ] as of phase 10H, corps get full cap on float, unsold shares go to bankpool on float. 
  - [ ] Prior to phase 6H corps par as 5-share if their home is not yet connected to their destination, 10 share otherwise
  - [ ] corps started as 5-share get 3 tokens
  - [ ] corps started as 10-share get 4 tokens
  - [ ] Phase 6H and later, only 10-share
  - [ ] Etat Belge is always 10-share
  - [ ] 5 share can use all par prices
  - [ ] 50% to float all corps (5-share defaults to 60)
  - [ ] token placed on map immediately upon float

**Operating Round**
- [x] OR structure is like 1830
- [ ] privates pay dividends
- [ ] 1 lay or upgrade per OR, corp may lay 2 yellow tiles (only yellow) in its first operating turn.
- [ ] Etat and SNCF do not get second yellow tile lay in their first operating turn.
- [ ] tokens are F20 per hex distance from nearest corp token. 
- [ ] trains may run to, but not through, Paris (like London in 1822)
- [ ] track may not be laid in the hexes surrounding Paris without consent from the corporation whose home station is adjacent to each hex (like London in 1822)
- [ ] no corporation can lay or upgrade track in Belgium (upper right portion of map) until Etat Belge has operated. 

**Train Buying**
- [ ] may not crossbuy before phase 6H
- [ ] Corporations with loans may only buy trains at or below face value
- [ ] Corporations with loans may only sell trains at or above face value
- [ ] L’Etat and the SNCF can only buy and sell trains at face value
- [ ] EMR
  - [ ] Corp must always own a train at the end of its operating turn, regardless of routes.
  - [ ] If the corp has insufficient money to buy a train, it must take a F500 loan. If this is still not enough, it may take a second loan. No more than 2 loans may ever be held by a corp.
  - [ ] corporation may not issue shares during EMR
  - [ ] if loans do not provide enough money, standard EMR applies. 
  - [ ] presidencies may change hands during EMR, except for the presidency of the corp that is EMR.
- [ ] If the SNCF (ONLY the SNCF) is forced to buy a train, it must issue its Bonds prior to taking out a Loan. Each SNCF Bond is worth F100. Any Bonds issued to pay for a train are placed in the bankpool, where players may buy them, or SNCF can redeem them. 
- [ ] SNCF pays bond interest to the bond holder. If in the bankpool, interest is paid to the bank. If bond is player-owned, player receives bond interest from SNCF treasury.

**Bankruptcy**
- [ ] All money raised for the corp remains in its treasury
- [ ] all remaining player holdings are placed in the bank pool. The 50% limit on shares in the bank is waived here, as is the restriction against presidencies in the bank pool.
- [ ] if the Etat or SNCF presidencies are sold during a bankruptcy and no one else has at least 2 shares, the corp is closed without compensation, and all tokens are removed from the map. It’s trains are placed in the bank pool.

**Loans**
- [ ] Loans are F500. 
- [ ] F50 Interest must be paid each OR after earnings are calculated but before they are paid.
- [ ] if the corporation doesn’t have the full interest in its treasury, the interest is withheld from the dividends directly.
- [ ] if this is still not enough to pay interest, enter EMR as above.
- [ ] share price moves left when loan is taken
- [ ] share price moves right when loan is paid

**National Railway Formation**
- [ ] Etat
  - [ ] possibly formed at phase 6H
  - [ ] Forms through merger of at least two trainless corporations after 2H rust
  - [ ] All corps (other than Etat Belge) that have operrated at least once and are now trainless merge in
  - [ ] No other corps may merge in
  - [ ] If only one corp is left trainless, merger does not happen and Etat does not form.
  - [ ] If Etat forms, first, all merging corps immediately convert to 10-share corps, with the remaining 5 shares being added to the treasury.
  - [ ] Starting with the president of the corp that bought the first 6H and continuing clockwise, holders of shares in merging corps exchange their shares 2 for 1 with shares in the Etat.
  - [ ] odd shares are discarded to the pool without compensation
  - [ ] First eligible player receives presidency
  - [ ] Etat treasury exchanges shares 2:1, discarding odd share if any.
  - [ ] the pool exchanges shares 2:1, discarding odd share if any
  - [ ] if there are not enough Etat shares to replace all merger shares, leftover shares are discarded without compensation.
  - [ ] any remaining unexchanged shares are placed in the Etat treasury
  - [ ] Etat starting price is the average price of the two most valuable corps merged in, rounded down to the nearest value on the top row of the market, to a minimum price of F82.
  - [ ] Share price is moved left once for each loan inherited by the Etat.
  - [ ] all home tokens on map are exchanged with Etat tokens
  - [ ] Etat may choose to keep up to one additional map token from each corp
  - [ ] Etat may have multiple tokens in Paris, only one in other cities
  - [ ] Etat receives all money and special abilities from merging corps
  - [ ] Etat receives an additional 3 tokens
  - [ ] Merged in corps are removed from play
  - [ ] Etat operates as long as at least 5 shares are out of its treasury
  - [ ] Etat operates this OR, as long as none of the merging corps have operated yet. Otherwise it will operate in the following OR.
- [ ] SNCF 
  - [ ] All rules are the same as formation of Etat, except as follows:
  - [ ] SNCF can form immediately after sale of first 10H and again after sale of first E
  - [ ] If not formed after sale of first E, SNCF does not form
  - [ ] Again, SNCF is formed if 2 or more corporations which have operated at least once are left trainless after rusting event.
  - [ ] Again, Etat Belge cannot merge in (but apparently Etat can, rules aren’t clear)
  - [ ] minimum price will be F110, rather than 82.
  - [ ] after replacing all home tokens, SNCF may replace up to two tokens per corporation.
  
**Game End**
- [ ] Ends after current set when the bank runs out
- [ ] Game ends immediately if all but one player bankrupt
