### ISSUE TITLE
18Mag Implementation Checklist

### ISSUE THREAD

**Issue by roseundy** [tobymao/18xx#2854]
### Map and Tiles

- [x] First pass map
- [x] Tile manifest
- [x] Double-sided tiles

### Draft Round

- [x] Player starting cash = 0
- [x] Players pick from minor companies and shares of corporations
- [x] All companies and 1-2 shares of corporations are on offer (based on player count)
- [x] Each player can only choose certain number of minors and shares (based on player count)
- [x] Order of choice is based on player count (rotating)
- [x] No bidding, no passing, and no cost to choose
- [x] Tokens are placed for minors at start of game
- [x] At end of round, any unchosen minors (and tokens) are removed from the game
- [x] Moves to first OR after end of round
- [x] PD goes to player would be next in rotation

### Subsequent Share Rounds

- [x] 1D stock market
- [x] 60% max corporation ownership by player
- [x] Certificate limits
- [x] Sell then Buy
- [x] First player to buy/acquire 2nd 10% share (from either IPO or market) becomes president
- [x] Cannot sell president cert (but usual transfers of presidency apply)
- [x] Sales move share price one left, independent of number of shares sold.
- [x] Share price moves one right if all shares in player's hands at end of SR
- [x] Minors do not count towards share limits 

### Minor Companies

- [x] 13 minors (not all in play)
- [x] Start with 2T, 50 Ft
- [x] 2 trains maximum
- [x] Don't need to own train
- [x] Forced 50/50 dividends
- [x] Variable number of "Terrain Tokens" that help pay for terrain costs
- [x] Operate in numerical order
- [x] Normal OR steps + new "Scrap Train" step

### Major Companies (Corporations)

- [x] Start with random share price (one of 5 possible)
- [x] Start with all shares in pool
- [x] Start in receivership and floated
- [x] Operate in share price order
- [x] Only OR steps: token, dividends
- [x] Tokens add +10 to city. May be laid in any open slot.
- [x] No token if no president
- [x] President determines how much of treasury (multiple of 10 Ft) is paid out.
- [x] Maximum is paid out if no president.
- [x] Variable share price movement based on amount paid out

### Laying/Upgrading Track

- [x] Can place one additional yellow tile by paying 10 Ft to the KSB (any order)
- [x] Number of mountain and river symbols represent terrain cost. Each symbol is 10 Ft.
- [x] Terrain costs are paid to SIK.
- [x] Terrain tokens can be used instead of paying out of treasury (SIK still receives money).
- [x] River restriction in F9. Only 7 or 8 tiles can be laid on F9 and only if it doesn't cross the river
- [x] "K" hex upgrades (any legal yellow can upgrade but green and brown require "K")
- [x] Non-restrictive upgrades
- [x] L32 and L33 have terrain costs on upgrade

### Trains and Phases

- [x] Four train types: 2T, 3T, 4T, 6T
- [x] Bought from either MAVAG or LdStEG corporations
- [x] All are available at start
- [x] Purchase of first train of type advances phase: Yellow (start) -> Green -> Brown -> Grey (end of game)
- [x] Can optionally scrap one or both trains

### Routes

- [x] Can pay RABA to increase value of one off-board
- [x] Can pay Ganz & Cie to convert one train to a "plus" train (e.g. 3T => 3+3)
- [x] Can pay SNW to allow one train to run to a mine
- [x] Mines don't count as a stop on route
- [x] Cannot run through mine unless using SNW
- [x] Mines pay directly to treasury
- [x] Cost of using rail cars (RABA, Ganz & Cie, SNW) is a function of phase and number used
- [x] A given rail car can only be used once per OR per minor

### End of Game

- [x] Game ends 3 ORs after SR after grey phase is triggered. SR occurs immediatelyt after OR where grey phase was triggered.

**Comment by jenf** [comment]
In alpha so done
