### ISSUE TITLE
Harzbahn 1873 Implementation Checklist

### ISSUE THREAD

**Issue by roseundy** [tobymao/18xx#3740]
### Map/Tiles

- [x] concession routes. Use icons.
- [x] cities (red frames)
- [x] mine/plant tokens on map. Use token-sized icons.
- [x] narrow gauge tiles
- [x] multiple reservations
- [x] marking WBE concession tiles
- [x] borders

### Premium Auction

- [x] Similar to 1860 start auction
- [x] used to determine Start Premium
- [x] set player order after auction based on reverse order of passing

### Start Auction Round

* Actually a Draft round
- [x] all 15 mines + 2 concessions on offer
- [x] in turn order, pass or buy 1 mine (if start auction) or 1 concession
- [x] use Start Premium
- [x] reduce Start premium if all pass and mines and concessions still on offer
- [x] end if all pass and Start Premium is 0
- [x] close unbought mines at end
- [x] player order doesn't change at end of Start AR
- [x] goes to Stock Round next

### Auction Round

- [x] in turn order, pass or offer 1 concession or 1 purchase option up for auction
- [x] minimum bid is 100 M
- [x] bid amount must be multiple of 10 M
- [x] ends when all have been auctioned or all pass
- [x] player order doesn't change at end of AR

### Stock Round

- [x] May form a RR company if player has concession
- [x] When forming a RR may buy 2nd share in same action
- [x] Newly formed RRs are 5-share
- [x] May form a public mining company if SR2+ (or HW in SR1) from two independent mines
- [x] When forming a public mine, one of the two mines must be owned by the player, the other requires consent.
- [x] Newly formed public mines are 2-share - shares go to former independent mine owners
- [x] Newly formed public mine initial stock price is average of component mine face values rounded down to nearest legal stock price
- [x] HW must always be formed from 2 "Vor-Harzer" mines, OK for other public mines to use Vor-Harzer mines
- [x] If HW is formed in SR1 one mine must be mine 12 (Blankenburg)
- [x] can buy 20% - 40% share of receivership corp (in one action) if player has bought purchase option in AR
- [x] presidency doesn't change if corp hasn't operated
- [x] cannot sell shares in SR1
- [x] president cannot sell shares in corp that hasn't operated below 20%
- [x] SR ends if all pass
- [x] Any unexercised concessions or purchase options are forfeit
- [x] New player order determined by cash on hand, keeping existing order on ties

### Tile Laying

* town: city on red-bordered hex
* village: town or city on hex without red border
- [x] some yellow single city tiles upgrade to green OO tiles
- [x] green OO tiles upgrade to brown double-slot single city tiles
- [x] reserve upgrades for tiles that are laid on concession routes but don't follow route
- [x] allow lay of the reserved tiles by the concession company out of phase
- [x] move concession icon to new tiles.
- [x] super-restrictive: all new track must be usable
- [x] red frame -> red frame only

### Independent Mine ORs

- [x] uses Minor class
- [x] OR steps: track, route, dividends, buy_trains, convert (close)
- [x] starts with default 1 Machine
- [x] determine if connected to normal gauge track
- [x] automatic production
- [x] automatic maintenance
- [x] force close if can't cover maintenance out of revenue and cash.
- [x] automatic 50/50 dividend
- [x] only one machine allowed at a time
- [x] can buy next highest machine if available, scrapping existing. must be bought from bank
- [x] can buy switcher from bank or from another company
- [x] when buying switcher from another company price is 1 to 2 x face value
- [x] when buying switcher from another company, maintenance costs may have to be paid. those costs may be paid by purchaser or seller
- [x] only one switcher allowed at a time. buying a switcher scraps an existing switcher
- [x] can voluntarily scrap a switcher
- [x] unconnected mines treat all machines as size 1
- [x] can optionally close
- [x] when closing: transfer any cash to owner, flip tokens to closed side, machines and switchers are scrapped

### Public Mine ORs

- [x] uses Corporation class (or subclass)
- [x] OR steps: track, assign_switchers, route, dividends, buy_mines, buy_trains, convert
- [x] no track laying
- [x] can move switchers between subsidiary mines
- [x] revenue is automated
- [x] insolvent if can't pay maintenance out of revenue and cash
- [x] withhold/50% dividend/100% dividend
- [x] pay pay value when buying an independent mine
- [x] must have space for purchased mine
- [x] must have consent from mine owner
- [x] when buying closed mine, token is flipped
- [x] machines must be bought from bank
- [x] receive n machines when buying size n machine, will replace machines of lesser size
- [x] number of switchers cannot exceed number of mines. surplus switchers are automatically scrapped
- [x] HW gets extra revenue, but can only buy "Vor-Harzer" mines
- [x] can only issue shares (up-convert) if all shares are held by players
- [x] can only change from 5-share to 10-share corp if director owns 2 shares
- [x] new shares are put in IPO
- [x] will receive more slots for mines when up-converting

### Railroad ORs

- [x] OR steps: track, token, route, dividend, buy_train, convert
- [x] first OR: must lay concession track and determine if concession is complete. no other track can be laid
- [x] first OR: must buy compulsory train or go insolvent. A compulsory train is the train size to service its concession
- [x] first OR: after buying compulsory train, presidency may change
- [x] can replace an inactive token from another corp for half price (50 vs 100). inactive token is returned to owning corp
- [x] can only have 1 token per hex
- [x] can't token out a concession route before it is built
- [x] dividend options same as public mine (withhold, 50% split, 100% pay)
- [x] insolvent if can't pay maintenance out of revenue and cash
- [x] no limit to number of trains and switchers, except only one diesel
- [x] can buy from other companies between 1 and 2x face value
- [x] can scrap any trains and switchers, except: last train cannot be scrapped (NWE must always have a 2 train)
- [x] can never scrap diesel
- [x] same restrictions as public mines when issuing shares
- [x] will receive more tokens when issuing shares (5-share to 10-share)
- [x] QLB special case: always has "local train" revenue of 60/90 - computed outside of normal route rules
- [x] stations unused in route are flipped to inactive side

### MHE

- [x] operation completely automatic
- [x] always last corp in OR
- [x] revenue = 100 * size of train
- [x] pays out 100%, no maintenance
- [x] owns only one train, starts with a 1 train
- [x] buys next available train at end of last OR of each set of ORs
- [x] once it buys a 5 train, it stops buying and share price stops moving (sales or dividends)

### Trains

- [x] D trains (railcars) are available at beginning of first full set of 3 ORs after 5 train/machine is bought
- [x] mines can only buy machines and switchers
- [x] railways can only buy trains and switchers
- [x] buying a switcher doesn't consume a train card. The size of switcher being sold is the size of the next train in the stack

### Phases

- [x] phase change on each new train/machine size bought. buying a switcher never changes phase

### Routes and Revenue

- [x] route endpoints: town or village with corp token or plant/open mine not blocked by other corp token
- [x] route must contain at least one corp token
- [x] route can not reenter a hex with a town or village
- [x] route cannot pass through village blocked by other corp token, except for concession route
- [x] route cannot pass through town - it must start or end there
- [x] an N train services N routes which must form a connected network
- [x] routes that use separate cities in an OO tile are not connected
- [x] concession route *must* be serviced
- [x] no routes, regardless of train, can reuse track
- [x] tokens unused by any of the routes are flipped to the "inactive" side
- [x] towns and villages with token receive marked revenue
- [x] towns and villages without token receive 10 M
- [x] towns and villages that are tokened out receive 0 M (only possible on concession routes)
- [x] town and villages earn revenue only once across all routes
- [x] open, non-blocked mines earn mine multiplier times size of largest train visiting it, 0 M otherwise
- [x] non-blocked plants earn specified value but only once across all routes
- [x] diesel route: must start and end at corp tokens
- [x] diesel: run to maximal connected network of diesel routes connected to concession route (exception: QLB requires diesel route network to include Quedlinburg (E20))
- [x] diesel: revenue is 10 M per town and village in diesel route network
- [x] diesel: *can* reuse track with "normal" trains

### Insolvency and Receivership

- [x] all players return shares to market
- [x] any shares in IPO are sold to market and proceeds go to corp treasury
- [x] reorg cost for insolvency for railway by not buying compulsory train: cost of next train from bank
- [x] reorg cost for insolvency for railway by not paying maintenance costs and no train w/o maintenance cost: cost of next train from bank. reorg cost is 0 if it has at least one train that has no maintenance cost
- [x] reorg cost for insolvency for public mine: cost of enough machines from bank to replace obsolete machines
- [x] if treasury is sufficient to cover reorg cost, then buy train/machines from bank and scrap all obsolete trains, machines and switchers
- [x] if not, convert from 2-share to 5-share and/or 5-share to 10-share and sell IPO shares to market until reorg cost is covered
- [x] if 10-share and reorg cost stall not covered, bank pays difference. treasury will be at 0. if bank payment larger than stock price, change share price as if it was a dividend.
* at this point corp is in receivership
- [x] can be re-opened in SR via Purchase Option
- [x] receivership mine in OR: production as normal, withhold w/o changing stock price, no machine/switcher purchase, no issuing
- [x] receivership RR in OR: no track, no tokens, follow rules for receivership routes, withhold w/o changing stock price, no train/switcher purchase, no issuing
- [x] receivership mine or RR can go back into insolvency if it can't pay for maintenance costs

### Questions

- [x] how does presidency change in OR (due to buying compulsory train) work with the Round structure?

### Decisions

* Will use icons for concessions, same as 18SJ
* Maintenance is calculated with revenue in route step
* Public mines just use the Corporation class
* Concession and purchase options are privates that can be auctioned and bought during the AR
* buy_mines reuses 18CZ buy_corporation UI
* mine (and submine) cards show matrix of possible revenues along with any machine and/or switcher
* added action and UI to allow moving switcher around in a PMC if it changes revenue
* diesel train revenue too hard to calculate automatically - punted to player

### Things to Tweak Eventually

- [x] mine and industry icon size too small
- [x] more useful open and closed mine icons + "unclaimed" icon at beginning of game
- [x] show map during initial draft
- [ ] MHE has a "president", this can be confusing
- [x] owned concessions and purchase options not called out as such on player card
- [ ] concession route not explicit on map
- [ ] better rendering of narrow track, current rendering can be hard to follow
- [ ] token coordinates not correct - at least prior to floating
