### ISSUE TITLE
1862 Implementation Checklist

### ISSUE THREAD

**Issue by roseundy** [tobymao/18xx#4818]
- [x] Add logos and settle on colors for companies
- [x] Randomize companies in play
- [x] Randomize and implement structure for train permits
- [x] Fix spreadsheet for IPO/treasury shares

### Parliament Rounds

- [x] Parliament round auction. Use concession auction from 1873, but adjust next player based on auction winner
- [x] Check for legal bid in Parliament round
- [x] Prevent starting auction if player already won a charter
- [x] Create method to see if a company can start (based on home tile)
- [x] Allow winner to to buy 2 additional shares
- [x] Auto buy of tokens on chartered company flotation

### Game Flow

- [x] Round structure, including 2 Parliament rounds at start
- [x] Game end: highest stock price. No LNER formation.
- [x] Game end: bank breaks (15000). No LNER formation.
- [x] Game end: LNER formation at end of OR set when H train bought

### Stock Rounds

- [x] Cannot sell shares bought during round (some complexity around Director change)
- [x] Can buy from pool, IPO or treasury
- [x] Half-price redemption when trainless (same as 1860)
- [x] Implement "ignore first share sold" and "ignore first two shares sold" rule on share price (not for Director)
- [x] Prices don't drop if company hasn't floated or after H train
- [x] Cert limit change after H train. No requirement to dump shares if over limit at that point.
- [x] Auto buy tokens when chartered company floats
- [x] UI to buy tokens when non-chartered company floats
- [x] Chartered company get 100% capitalized on flotation. Nothing for non-chartered.
- [x] Deal with missed obligations
- [x] Normal priority deal rules

### First OR

- [x] place home token
- [x] can boot most recently placed token if, after upgrading home tile, no room for home token

### Track Laying and Tokening

- [x] Add "hidden" tiles to manifest to deal with towns on "plain" track and hide from Tiles tab
- [x] 1 yellow N
- [x] OR 2 other yellows
- [x] OR add a town to any tile on board (using hidden tiles)
- [x] OR upgrade a tile
- [x] OR add station marker in London
- [x] Some track on the new tile must be reachable
- [x] Upgrading town track: remove corresponding "plain" track
- [x] Upgrading town track: restore "plain" track if upgrading to brown
- [x] Ns on Ns
- [x] Ys on Ys
- [x] Special handling of Harwich and Ipswitch
- [x] Adding a station marker in London is in place of any other track or token laying. Basically prohibit tokening in London if laid track.
- [x] Use markers on home tiles instead of reservations.

### Routes and Running Trains

- [x] All routes: cannot begin/end at towns
- [x] One route must include home token (same as 1860)
- [x] All routes must intersect (same as 1860)
- [x] Can only run trains with corresponding permit
- [x] Different routes may reuse track, single route may not
- [x] Single route may not run blue-blue or red-red
- [x] Routes cannot run into London without corresponding token
- [x] Each revenue location (including offboards in same group) is only counted once for revenue
- [x] Freight Trains: train distance is number of hex crossings
- [x] Freight Trains: only count start/stop revenue locations
- [x] Freight Trains: bonus for "as the crow flies" intervening hexes between start/stop. For red/blue termini, count between hexes leading to red/blue and add 1 per red/blue. Bonus is $20/hex ($30/hex if blue terminus)
- [x] Freight Trains: non-permanent trains, < 6 distance ( < 5 distance if playing shorter variant), MUST connect to another freight train (if any) end-to-end
- [x] Local and Express Trains: method for recording "skipped" cities/offboards in run_routes action. Possibly store in revenue string or connection_hexes
- [x] Local Trains: distance is number of cities
- [x] Local Trains: cannot visit offboards
- [x] Local Trains: count N cities (out of M) and all towns. Cycle to change, similar to halts in 1860.
- [x] Local Trains: earn $10 subsidy for each hex in all Local Train routes (i.e. no double-counting of any hex)
- [x] Express Train: train distance is number of cities/offboards
- [x] Express Train: count N cities/offboards (out of M) and ignore towns (same cycling as Local trains)

### Dividends

- [x] payout or withhold only
- [x] multi-jump share increases base on revenue and share price
- [x] George Hudson Maneuver and UI (separate step between run_routes and dividend steps? or checkbox?)
- [x] George Hudson Maneuver can use local train subsidies from current run_routes

### Buying Trains

- [x] Can buy trains of any type
- [x] Can buy from other companies but at full price, unless on subsequent phase, in which case half price
- [x] Cannot buy trains if at or over limit
- [x] Train warranties

### Forced Train Purchases

- [x] Sell min number of stock in treasury, but sold at full price, and only if it could afford train if it does so
- [x] then, refinance (similar to a Merger)
- [x] for above: must be train from bank
- [x] then, bankruptcy

### Bankruptcy

- [x] Outstanding shares are sold at current half share price
- [x] Director share back to IPO with original permit
- [x] Trains removed
- [x] Available for restart in next PR/SR

### Stock Redemption

- [x] Corporation (chartered or unchartered) can buy one share of stock from pool at current price 

### Mergers

- [x] At beginning and end of OR
- [x] Only if connected to other RR
- [x] Requires consent
- [x] Active player determines which company will survive
- [x] Move any IPO shares to pool
- [x] Calculate new share price
- [x] Director with less than 60% in combined company must trade in Director share for 3 ordinary shares from pool if possible. If not possible, all ordinary shares are returned to pool and Director share becomes an option at 30% - 50%
- [x] All players return half of combined shares to pool, non-surviving company first, odd total shares result in "option" share 
- [x] In player order (companies acting last):
- [x] - Trade non-survivor shares (whole or option) for survivor shares, first from bank, then from following players
- [x] - Any non-survivor shares remaining are sold at new share price (or half for option shares)
- [x] - Ordinary option shares are can be sold at half share price (rounded down) or redeemed for half share price (rounded down)
- [x] - 30% option (former Director share): sold or redeemed for Director shareat 1.5x of share price
- [x] - 40% option (former Director share): sold for 2x share price or redeemed for Director share at share price
- [x] - 50% option (former Director share): sold for 2.5x share price or redeemed for Director share at half share price
- [x] Determine new Director
- [x] New par price (highest valid par price less than or equal to current share price) in chartered area if both were chartered companies, non-chartered area o.w.
- [x] Treasury, trains and permits moved to survivor
- [x] Survivor gets unused tokens from non-survivor
- [x] Non-survivor tokens in cities with survivor token are lost
- [x] Non-survivor tokens are replaced with survivor tokens
- [x] Any tokens in excess of 7 on the board are removed at Directors choice
- [x] Trains over train limit are NOT discarded

### Refinancing

- [x] Similar to Merger, except only one company
- [x] Share price doesn't change
- [x] Company receives 10x par price (not current price)

### Receivership

- [x] Operated by majority shareholder (!), ties broken by distance from PD
- [x] Cannot build track or tokens
- [x] Must withhold
- [x] Must buy train from bank if able (only for type corresponding to permits in Express-Freight-Local order) once per OR
- [x] Goes bankrupt if no train at end of OR

### LNER

- [x] No Parliament rounds
- [x] No track or tokens
- [x] Cannot start companies in SR
- [x] All IPO shares moved to pool
- [x] No inter-company train buying
- [x] Bank breaking will not end game (share price can still end it)
- [x] After LNER forms: 3 more ORs
