### ISSUE TITLE
[1840] Roadmap

### ISSUE THREAD

**Issue by Zwergenpunk** [tobymao/18xx#4994]
**Configuration and map**

- [x] Meta
- [x]  Map
- [x] City Corporations
- [x] Major Corporations
- [x] Minor Corporations
- [x] Private Companies
- [x] Train Configuration
- [x] Cert Limit
- [x] Count of trains depending on player count
- [x] End of game

**Map and Tiles**
- [x] BasicMap
- [x] Special Icons
- [x] Purple Hexes
- [x] All Tiles including orange framed

**Trains**
- [x] Add trains

**City Corporations**
- [x] Logos
- [x] Basic Configuration
- [x]  Immediately floated at given value
- [x] Tokens on map 
- [x] No Presidency share

**Major Corporations**
- [x] Logos
- [x]  Basic Configuration
- [x] Can own Minor Corporations
- [x] Cannot own trains
- [x] Always Market Price

**Minor Corporations**
- [x] Logos
- [x]  Basic Configuration

**Private Companies**
- [x]  Basic Configuration
- [x] Auction Round
- [x] Starting Player Selection after Auction round
- [x] Bonus Abilities
- [x] Return/Sell to Bank for face Value

**Stock Market**
- [x] Market Values
- [x] Every player needs to bid on one major corporation
- [x] Movement when Share sold
- [x] Movement when sold out
- [x] Player order

**OR**
- [x] Company Rounds and Line Rounds

**Company Rounds**
- [x]  Tram Export
- [x] Company Order
- [x] Dividend of Major corporations
- [x] Multipler for City Corporation Dividend 
- [x] Dividend of City corporations (auto routing?)
- [x] Buy a tram for minor corporations
- [x] Player Loan
- [x] Auctioning Minor Companies
- [x] "open" new Minor Companies for next CR
- [x] Trains may be moved to another corporation
- [x] City routes need to start in one of their outer tokens

**Line Rounds**
- [x] move in ascending order (like 1822)
- [x] Track and Token in same step
- [x] Bonus actions
- [x] Upgrading of purple tiles
- [x] Upgrading of red tiles
- [ ] Red and purple tiles can only be layed when connected
- [x] Tokens of city corps may be removed for 40
- [x] Run routes
- [x] Scrap trains when selecting routes
- [x] dividend is payed to owning major corporation
- [x] dividend only tokened cities and halts
- [x] Maintainance Cost for tram
