### ISSUE TITLE
18KA checklist

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#5664]
- [ ] Private randomization
- [ ] Corporation removal
- [ ] Forced 20 share national
- [ ] ObsoletedBy counts as non-permanent
- [ ] Pullmans - Count against train limit
- [ ] Pullmans - Can be voluntarily discarded
- [ ] Pullmans - Can be bought only at face value
- [ ] Pullmans - Unsold ones discarded to open market on color change
- [ ] Pullmans - Do not fulfill obligation to own a train
- [ ] Pullmans - Are not eligible for trade in
- [ ] Mining bonus neutral token
- [ ] Engineers can be used
- [ ] Engineers can be used from other corporations
- [ ] E tile locks
- [ ] Prototype Maglev exchange
- [ ] Bribes IPO share exchange
- [ ] Underground Connections token steal
- [ ] Underground Connections corporation par
