### ISSUE TITLE
18Carolinas Implementation Checklist

### ISSUE THREAD

**Issue by roseundy** [tobymao/18xx#5753]
### Stock Rounds

- [x] Sell/buy privates to/from bank
- [x] Can sell president certificate to bank
- [x] Can only buy 10% shares

### Track Laying

- [x] Lay 1-2 yellow or upgrade 1
- [x] Standard track only in North, Narrow track only in South until Phase 5
- [x] Auto-upgrade of all C-hexes to brown when entering Phase 5
- [x] Optional conversion of all narrow-gauge track to standard between cities/offboards after Phase 5. UI to do this?

### Train Power

- [x] Replace buy_train with buy_power. Probably needs new UI.
- [x] EMR rules, including double cost
- [x] Personal bankruptcy may cause receivership
- [x] Phase changes
- [x] Power degradation
- [x] Modify Info tab
- [x] Modify Corporate cards

### Running Routes

- [x] Train +/- to run_routes
- [x] Train size +/- to run_routes (can this be done automatically?)
- [x] Check total train sizes against train power
- [x] Cannot have trains with smaller size than minimum train
- [x] Single train cannot use multiple gauges

### Dividends

- [x] Share price movement rules based on revenue

### Receivership

- [x] Receivership rules

### Game End

- [x] Game end on bank breaking
- [x] Game end on reaching 350 share price
- [x] Game end if all but one player is bankrupt
