### ISSUE TITLE
[18Rhl] Implementation checklist

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#5784]
- [x] Base files
  - [x] Map
    - [x] Basic structure
    - [x] Random setup of Coal and Steel mill (one of 9 different combinations)
    - [x] S and K tokens (simplified only?)
  - [x] Tiles
    - [x] All tiles configured
    - [x] Upgrades of lettered
    - [x] Orientation of Rhine Metropolis cities
    - [x] Tile 935 special in hex E8
  - [x] Stock Market structure
  - [x] Trains
    - [x] Standard trains
    - [x] Rheingold-Express 
  - [x] Corporations
    - [x] CCE starts with two stations
    - [x] RHE gets 3 shares in market when parred
    - [x] RHE gets value of 3 shares when there is a link between Aachen and Köln
    - [x] Icons
    - [x] Simplified Icons? 
  - [x] Companies
    - [x] Private 1
    - [x] Private 2
    - [x] Private 3
    - [x] Private 4
    - [x] Private 5
    - [x] Private 6 
  - [x] Meta
  - [x] Share limit, certificate limit, starting money, total money
  - [x] Wiki
- [x] Initial auction pretty similar to 1830
- [x] Revenue and dividend payment
  - [x] Railroad ferry across Rhine (Trajekt)
  - [x] Handling of towns for revenue
  - [x] Towns may not be termini
  - [x] IPO shares means revenue paid to company, market to bank
  - [x] The Montan Bonus
  - [x] Östliches Ruhrgebiet
  - [x] Der "Eiser Rhein"
  - [x] Rheingold-Express
- [x] Train buy
- [x] Emergency funding
- [x] Game end
  - [x] Bankruptcy and receivership
  - [x] Becoming director of corporation in debt
- [x] Stock Market details for SR/OR 
- [x] ...
- [x] Variants
  - [x] Optional 2-train (compare 1893)
  - [x] Lower total Starting Capital (for 3 or 4 players only)
  - [x] Promotion tiles
  - [x] Ratingen variant
    - [x] Changed components
    - [x] Implement private 1
    - [x] Rule changes
- [ ] Miscellaneous
  - [x] GVE via private will add PAR to treasury for third when presidency shared bought. Update private text.
  - [x] RHE will start treasury with winning bid for private. Update private text.
  - [x] RHE PAR 70, 75 or 80. Update private text.
  - [x] When corporation floated - move shares to market?
  - [x] Set to alpha
  - [x] Set to beta
  - [ ] Set to production
  - [x] Fixture with (at least) alpha version of game.
  - [x] Fix spelling errors on private 6
  - [x] Consider to add an ability/text to RhE that shows how much will be added then link is built
  - [x] Improve route presentation to separate towns from cities/offboard
  - [ ] Maybe it works better if corporations start with 10 shares in Treasury? And when brown phase - any with unsold shares becomes IPO instead.
  - [x] (Reported by @benjaminxscott:) No. 1 Angertalbahn, shouldn't reachable and closed_when_used_up be set?
  - [x] Brown corporations that float: Do not move up 1 step like non-Brown float do (check implementation)
  - [x] Discuss Orange corporation with designer
  - [x] "Unknown method sym for 'Corporation CME'" thrown in pinned game after Private 2 build, and pass of token
  - [] Freeze issue (closed).
  - [ ] Is it a problem to do both Private 2/4 - regular build, and regular build - Private 2/4? (Or is it pinned games only?)
  - [x] Add status/event for brown capitalization, to make this more visible
  - [x] Promo tile can clearly (physical game) have only one allowed orientation. Check implementation.
  - [x] It is still unclear if ferry tiles are handled in a correct way. Investigation ongoing. ((2022-03-19)) Reworked ferries as can be seen from #7384.
  - [x] See #7497 - this is a potential improvement of the implementation in the future. But no action as of now.
