### ISSUE TITLE
18VA Checklist

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#5829]
- [x] Initial Commit
- [x] Bankruptcy
- [x] Chain reactions like 1846
- [x] Company can be reopened after closing
- [x] Privates
- [x] Logos
- [x] Trains and revenue
- [x] Fix ports (they only count if you have a token in the corresponding city, and are doubled with freight or doubler trains)
- [x] limit port to port
- [x] Change IPO to Treasury if possible
- [x] Post ISR player reorder
- [x] Rules Link
- [x] Wiki Page
