### ISSUE TITLE
18Scan implementation checklist

### ISSUE THREAD

**Issue by vandamm** [tobymao/18xx#6841]
This is just a reminder for me on implementing all of the 18Scan features.

Rules link: https://boardgamegeek.com/filepage/233108/18scan-rules-v10-dtd-30-sep-2005

# Initial stock round

- [ ] Extract common code from 1860 initial auction to Game::Step::BidToBuyAuction (different name maybe?) and apply it to both 18Scan and 1860
- [ ] If everyone passes on first bid, player with Priority Deal is assumed to have won the auction and must buy one item, at which point the ISR ends.
- [ ] If everyone passes on consecutive bid, ISR ends
- [ ] If ISR ends with unsold items, they are added to the bank pool and can be bought at face value

# Private Companies

- [ ] Three Mainline private companies grant owner a minor company (1, 2 or 3)
- [ ] Never sold to corporations
- [ ] Mine token can be bought by corporation/minor from owner's Mine private for K50, closing the company
- [ ] 2 Ferry tokens can be bought by different corporations/minors from owner's Ferry private for K20. When both are bought, close the company
- [ ] If Ferry/Mine is closed on phase 5, unsold tokens are placed to bank pool, where they can be bought at face value

# Stock Round

- [ ] Shares are always bought on market price
- [ ] Number of shares sold needed to float depends on game phase
- [ ] Capitalization type changes from incremental to full on phase 5
- [ ] Players may not choose to sell multiple shares of a single Corporation’s stock as multiple transactions in the same turn of a Stock Round.
- [ ] What happens if corp's president cert is bought in phase 4, but it floats in phase 5?

# Operating Round

- [ ] Off-board hexes with cities cannot be included in routes unless they are tokened by running corp
- [ ] Can only buy one train of a type per turn from the pool
- [ ] Until phase 5, if a tile lay by any entity connects a minor to its destination, perform a destination run (see Destination Run)
- [ ] Y tile upgrades: Helsinki 5 - 622 - 582, Oslo 5 - 622 - 623, Stockholm N/A - 622 - 582
- [ ] Corp can buy tokens from its president's privates during Token Placement step
- [ ] Can only buy one train of a type from the Bank per OR
- [ ] 

# SJ

- [ ] Can only be parred at K100
- [ ] Shares can be bought in SR in any phase
- [ ] Floats after 50% of shares are in player's hands after phase 5
- [ ] Cannot float until phase 5
- [ ] If 50% of shares are bought when phase 5 starts, SJ floats immediately, but operates only in next OR
- [ ] Receives K700 from the bank on float
- [ ] Receives all money, trains and tokens from three minor companies on float
- [ ] During formation if multiple minors have token in same hex, only one token is left on the board
- [ ] Has a train limit +1
- [ ] If minors have tokens from private companies, they are transferred to SJ

# Minor Companies 

- [ ] Are bought from privates auction
- [ ] Receive its cost in treasury
- [ ] Have train limit 2 less than corporations
- [ ] Are closed in phase 5
- [ ] Have a destination hex
- [ ] 

# Destination Run

- [ ] Transfer turn to owner of a minor company that destinated
- [ ] Allow to place a destination token for free
- [ ] Assign routes to trains and add K80 bonus to earned revenue, then pay it out as usual
- [ ] Transfer turn back to the company that made the connection

# Destination run edge cases:

- [ ] A tile lay or upgrade may simultaneously connect two or more Minor Companies. It is then possible that one of the Minor Companies, in the course of performing its Bonus Run, may place its Destination token so 
as to cut off a subsequently running Minor Company from its Destination. Nevertheless, when the other Minor Company conducts its Bonus Run, it is allowed to place its Destination token, even if it can no longer trace a route to it from its home station.
- [ ] If a Minor Company’s Destination token should be placed while the tile in the Destination hex is still yellow, and the placement would not normally be allowed (either because a Company has already placed a token there, or—in the case of Oslo—because it is reserved for tire NSB’s home station), tire Destination token is placed at the edge of the tile instead. When the tile is upgraded to green and gains a second City circle, the Minor Company’s token occupies the second City circle: no other Company is permitted to claim it. While on the yellow tile, the token functions in all respects as if it occupied a City circle other than the existing one.
- [ ] If the Destination city has been upgraded to a green tile prior to the Minor Company’s establishing a connection to it, and the City circle that the Destination token would normally occupy has been filled, the opportunity to place the Destination token is lost: the space is only reserved so long as the tile is yellow.
