### ISSUE TITLE
18GB Implementation Checklist

### ISSUE THREAD

**Issue by andypymont** [tobymao/18xx#6982]
# 1 Setting Up
* [x] Map
* [x] Map: Grimsby/Hull hex not currently correct to the physical game
* [x] Tiles
* [x] Scenarios: different corporations, private companies, and trains depending on the player count
* [x] Two scenario options each for 2- and 4-player games
* [x] Scenario also determines player starting cash and certificate limits
* [x] Scenario also determines whether grey tiles are used
* [x] The LNWR and half (rounded down) of the other corporations in the game are available in stock round 1, and the others cannot be parred until stock round 2

# 2 Private Railway Auction
* [x] During your turn you either bid on a company or pass
* [x] Minimum price is the face value of the company or £5 more than the current highest bid
* [x] Bids must be in increments of £5
* [x] You can only pass if you are winning an item (2 items in 2-player game) or if all items have a bid
* [x] When all players pass, items with bids are sold to the high bidders and all other items reduce in price by £10
* [x] After the first full round of passes, the bidding requirements are relaxed and any player may pass on their turn
* [x] If an item costs £0, the next player in the auction must "buy" it
* [x] Player order after the initial auction round is least money to most money, tied player with the most private companies goes first, players still tied retain their order from the auction

# 3 Corporations and Shares
* [x] Corporations begin as 5-share (40% president's share, three 20%shares)
* [x] Players may not buy more than 60% of a corporation from the IPO (but may buy up to 100% when buying from the market)
* [x] Shares may be sold to the open market without limit, including selling the president's share

# 4 Stock Rounds
* [x] On their turn, a player may sell then buy shares
* [x] Alternatively, instead they may convert a corporation to 10-share and then optionally buy one share of that corporation from IPO or market
* [x] When a corporation converts, its price drops two steps, it gains five times the new share price in additional capital, and 5 new shares are placed in the market. The president's share is now a 20% share and the other shares are 10% shares
* [x] When a corporation converts to 10-share, it gains 2* additional station tokens
* [x] Share prices drop one step for each share sold
* [x] After the start of the grey phase, the price of shares only drops when the president sells
* [x] Players receive only 50% of the value for the sale of shares of corporations which own no trains (rounded down)
* [x] In the first phase, a corporation floats immediately with 40% sold (just the president's certificate)
* [x] In the green and blue phases, a corporation floats once 60% is sold
* [x] In the brown phase, all new corporations are 10-share and float once 60% is sold
* [x] The player order for the following stock round is set in the order of passing in this round

# 5 Operating Rounds
* [x] Corporations in receivership become insolvent at the beginning of their operating turn
* [x] A corporation may lay two tiles each operating round, but only one may be in a tile with one or more cities
* [x] A corporation may lay one station token each operating round, either before, between, or after its tile lays
* [x] Insolvent corporations and corporations in receivership do not lay tiles or place tokens
* [x] Yellow plain track and yellow town tiles are unlimited in quantity
* [x] When laying a yellow tile in a hex with no tile, if the tile has more than one city, place any existing station token in that hex in a city not connected to any track if possible
* [x] Track-laying is restrictive: the corporation laying the tile must be able to run new track on the tile, even if upgrading a city
* [x] When laying or upgrading a tile so new track runs into a hill hexside, a corporation must pay £50 to the bank for each such hexside
* [x] When laying a blue estuary tile, a corporation must pay £50 to the bank. These tiles may only be placed on the indicated hexes, only from the blue phases onwards, and with only one rotation each

# 5.4 Run Trains
* [x] *A*+*B* trains run a total of *A*+*B* stops, of which only *A* may be cities and offboard locations
* [x] *A*X trains run a total of *A* cities, passing through unlimited towns without counting them for revenue
* [x] *A*X trains pay a bonus revenue equal to £10 times the distance (as the crow flies) between the start and finish hex (including the finish hex but not the start hex)
* [ ] North-South and East-West bonuses are paid if a corporation can trace a route between appropriately-marked offboards such that every piece of track on that route is included in the route of one or more of the corporation’s trains.  Multiple trains may be used to make a connection, provided their routes connect or cross. A corporation may claim both bonuses, or the same bonus more than once
* [x] A company using the marked path on an estuary tile receives a bonus as shown on the tile
* [x] Insolvent corporations lease a notional train of the cheapest type available new; leasing a train of a new type does not trigger a phase change

# 5.5 Distribute Income
* [x] IPO shares pay dividends to the corporation. Open market shares do not pay anyone
* [x] If a corporation withholds, its share price moves 1 space down
* [x] If a corporation pays dividends, its share price moves up - at least once, but two, three, or four times if the total revenue is at least two, three, or four times the current share price
* [x] A company which is insolvent or in receivership must withhold revenue

# 5.6 Purchase trains
* [x] Inter-company train purchases are at a price between £1 and twice the face value of the train
* [x] A corporation may not purchase the last train of another corporation unless it is itself trainless before the purchase
* [x] If a corporation does not own a train, does not buy one from another company, and does not have sufficient money to buy the cheapest available new train, it enters emergency money raising
* [x] A five-share corporation in emergency money raising may convert to a ten-share company, dropping three steps instead of two
* [x] The president may buy a share during conversion, even though this is happening outside of a stock round
* [x] After converting during EMR, the corporation must buy a new train if it can afford one
* [x] If a corporation cannot or does not want to convert to 10-share to buy a train, it declares insolvency
* [x] Corporations in receivership may not buy trains from other corporations
* [x] Corporations in receivership will only buy a new train if they do not already own trains, and only buy a single train
* [x] Corporations in receivership buy the most expensive available train if there is more than one available
* [x] Corporations in receivership which are 5-share corporations will convert if they cannot afford the cheapest train in the depot
* [x] Corporations which ends their turn without a train become insolvent
* [x] Insolvent corporations that buy a train immediately stop being insolvent

# 5.8 End of OR
* [x] If no new trains were purchased this OR, the cheapest available new train is removed - this may trigger phase changes

# 6 Phases
* [x] Different train limits for 5- and 10-share corporations, based on phase
* [x] The purchase of the first of each of the *A*X trains triggers the availability of the next type of train
* [x] Once the grey phase begins, remove all unstarted corporations along with one 6X train for each of them

# 7 Ending the Game
* [x] Bank is unlimited, game end triggered by final train purchase or share price in game-end section

# 8 Private Companies
* [x] Private companies block their hex until voluntarily closed by their owner
* [x] Voluntary closure can happen any time after SR1
* [x] From the blue phase onwards, corporations may ignore this blocking and force a company to close by laying a tile in its hex
* [x] On closing, a company pays its revenue to its owner one last time, and then its revenue and value become £0
* [x] LB 'marries' the owner to the LNWR corporation: nobody else may buy the LNWR presidency, and the LB owner may not buy any other shares until they buy the LNWR presidency
* [x] AF and LS, once closed, allow a corporation owned by the same player to make an additional tile action once during the game in the relevant hex 
* [x] GN and MC reserve a token spot in the relevant city until the blue phase, and once closed allows a corporation owned by the same player to lay a free station token in the relevant hex
* [x] GN and MC token costs £50 if teleporting, otherwise it is in the usual price (i.e. free for CR, £50 for other corporations)
* [x] GN and MC allow placing a green city in the hex after tokening, even before the green phase
* [x] When using the GN or MC, a 10-share CR may use one of the £50 tokens instead of its £0 token, saving the free token for later
* [x] CH, LM, and SD give an income bonus for the relevant location once closed
* [x] TV, once closed, allows a corporation owned by the same player to lay the Severn Tunnel estuary for free
* [x] Second-edition price and revenue changes

# 9 Corporations
* [x] CR's first station token is free
* [x] LYR as a 5-share has no other station token besides its home
* [x] MSLR as a 5-share has no other station token besides its home
* [x] NBR receives only one extra station token on conversion
* [x] GER, GSWR, MR, NER, and SWR may directly lay a green tile in their home cities, even before the green phase
