### ISSUE TITLE
18 Los Angeles 2 checklist

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#7110]
- [x] map changes
- [x] public company (corporation) changes
- [x] private company changes
  - [x] for 2E, CHE's _total_ discount should be $20, never $40; Alhambra has water and mountain, but plenty of other hexes have multiple waters or multiple mountains, and the discount in those cases is meant to be $20 as well
- [x] new private companies
    - [x] Angeles Public Dump
    - [x] LA Paving
    - [x] Redondo Junction
    - [x] RKO Pictures
- [x] corporation removal
- [x] private company removal
- [x] home station placement
- [x] two player corporation removal
- [x] PER home chosen when parred

**Comment by michaeljb** [comment]
will check the boxes above when PRs are merged, I think this is all that's missing from my local code:

* setting PER's home when parred
* new private company abilities
* manual testing
* validate existing 1846 and 18LA1 games

**Comment by michaeljb** [comment]
Update: will not being to alpha without the new private abilities

**Comment by michaeljb** [comment]
screenshot for my current approach for implementing Redondo Junction (will include this on the PR) ![Screenshot from 2022-03-05 17-27-12](https://user-images.githubusercontent.com/1045173/156904896-8b2a8045-4ae5-4096-8b1d-7741bb02d8ba.png)

**Comment by michaeljb** [comment]
My branch `18LA2-dump` has the necessary fixes, but will have merge conflicts with the CHE changes so I'll wait for #7413 to be merged before opening a new PR (since I've already force-pushed the updates, GitHub does not allow me to simply reopen #7412)
