### ISSUE TITLE
18WE Implementation Checklist

### ISSUE THREAD

**Issue by andypymont** [tobymao/18xx#8661]
_Listed by rules section._

Components
* [ ] Tiles
* [ ] Stock market
* [ ] Corporations (names, charters, tokens)
* [ ] Trains

2 Sequence of Play and Phases
* [ ] Phases per phase table 2.3
* [ ] Yellow and green city tiles available in phase 1
* [ ] All town tiles available from phase 1
* [ ] ORs per SR determined by game progress rather than phases; show this in Timeline tab
* [ ] 1 OR per SR at beginning of game
* [ ] 2 ORs per SR once 10 minors floated
* [ ] 3 ORs in the final set once game end triggered
* [ ] Train limit: majors two per license type, minors two total
* [ ] All phase 1 trains available at the start
* [ ] Purchase of the final ⇑ train makes all next-phase trains available
* [ ] Purchase of the final D⇑ train (/start of phase 4) makes all E/F/G/H trains available
* [ ] First E/F/G/H train purchased begins phase 5

3 Late and End Game
* [ ] End-game trigger from stock market zone
* [ ] End-game stock changes: new cert limits, no sales needed over limit, sales don't change share prices, remove concessions, minors integrate/bankrupt
* [ ] Operating changes in final OR set: no new track or stations, no mergers
* [ ] End-game trigger: completion of final OR once triggered by share price as above
* [ ] End-game trigger: corporation hits top of stock market - finish this OR only
* [ ] Shares of trainless corporations are worth 50% for end-game value

4 Map
* [ ] Map
* [ ] Premier Offboard Locations: London and Constantinople. No running a train to or through these locations without a token in them.

5 Track Tiles
* [ ] Track tiles are unlimited
* [ ] Train routes may not begin or end at a town
* [ ] Exception: Freight trains combining to make a single run, as long as neither end point is a town

6 Tokens
* [ ] Station token cost: 1 action/25f in home region, 2 actions/50f outside home region, 3 actions/75f premier offboard

7.0 Regions
* [ ] French corporations: track action subsidy
* [ ] Germanic corporations: industry subsidy
* [ ] Southeastern corporations: warranty subsidy

8 Subsidies (corporation special abilities)
* [ ] Warranty subsidy: 2 free warranties in train purchasing phase
* [ ] Track action subsidy: 2 free track actions every OR
* [ ] Industry subsidy: +20 or +30 marker (depending on flotation order) that must be placed in a home region city on first operating. One industry marker maximum per city.
* [ ] Treasury money subsidy: once per OR, receive money equal to highest connected city in home region
* [ ] Share reservation subsidy: director reserves an extra share once before the late game

9 Licenses
* [ ] Four license types: express, freight, inter-city, and regional
* [ ] Licenses assigned at game start based on scenario
* [ ] Corporations may only token outside of home region if they have an express or freight license
* [ ] Intercity and regional trains only operate in a corporation's home region and may not cross regional borders

10 Trains & Warranties
* [ ] Train limit of 2 per license type
* [ ] Permanent trains are unlimited in quantity
* [ ] A warranty guarantees one run of a train
* [ ] Maximum of 3 warranties per train
* [ ] Each non-permanent train comes with one (⇧) or two (⇩) free warranties
* [ ] Whenever a corporation buys a train from the bank, it may choose whether or not to receive the free warranties and may purchase additional warranties for 50f each
* [ ] After a corporations runs routes, all of its trains lose one warranty each, whether or not it ran for any revenue
* [ ] Express trains: count the given number of tokened cities.
* [ ] Freight trains: cross the given number of hexsides. Train specifies the revenue per hexside crossed as the crow flies.
* [ ] Intercity trains: count the given number of cities. Train specifies the revenue and treasury money scored per city.
* [ ] Regional trains: count the given number of cities. Train specifies the revenue and treasury money scored per town.

11 Corporations
* [ ] Each corporation has a 30% president's certificate and seven 10% certificates
* [ ] Each corporation also has 12 station tokens

12 Setup
* [ ] Boom markers: Two random offboards receive +10 (game start)/+20 (brown onwards) value.

13 Standard Scenario
* [ ] Starting capital and cert limit per table in 13.1
* [ ] Subsidies allocated by region
* [ ] Each region has a primary license pool of 2 freight, 2 express, 2 regional and 2 intercity licenses
* [ ] First 3 corporations per region are available from game start and receive a license from their home hex pool
* [ ] Next 2 corporations per region are available from phase 2 and receive a license from their home hex pool
* [ ] Final 2 corporations per region are available from phase 3 and receive a license from their home hex pool

14-15 Stock Rounds
* [ ] Must sell down to cert limit on your turn, except during the final SR
* [ ] Certificate limit is adjusted in the final SR
* [ ] Sell then buy
* [ ] No selling of shares acquired (bought or received via integration) this SR
* [ ] After selling, the buy action can be used for one of: buy a share, begin the auction of an unstarted corporation, integrate a minor into a major for an available 10% share, or convert a minor into a major
* [ ] Player order for next SR is based on pass order in this SR
* [ ] Buy reserved share only with permission of president
* [ ] IPO shares bought at par price, market shares at current price
* [ ] Trainless corporation shares sell at half price
* [ ] Sales zig-zag down the share price per share sold
* [ ] Exception: Sales of shares in unfloated corporations don't drop the price
* [ ] Share price above 200 or below 40: non-president sales ignore the first share sold for price changes
* [ ] No limit on shares in bank pool, including selling the presidency
* [ ] When the SR ends, the number of ORs in the upcoming set is determined based on number of corporations floated in the game so far

16 Auctions
* [ ] Minimum bid of 0 for major
* [ ] Minimum bid of 140 for minor with express/freight/regional license
* [ ] Minimum bid of 100 for minor with intercity license
* [ ] Minimum bid of face value for concessions
* [ ] Must raise bid by 5f
* [ ] Once you pass you are out of the auction
* [ ] Winning bid goes to treasury for minor, otherwise to bank
* [ ] Concessions available from second stock round
* [ ] 8 x Small vertical concession: allows capitalizing one major or minor for 50f
* [ ] 6 x Large vertical concession: allows capitalizing one major or minor for 100f
* [ ] 6 x Major concession: allows reserving a president's certificate for a future SR, unless vetoed by a player who can afford to buy it outright
* [ ] Once purchased, the major concession blocks starting the corporation this SR (including by the owner). It may be started in the following SR
* [ ] If a player vetoes a major concession purchase, an auction immediately begins with that player bidding 165f.
* [ ] Major concession vetoing may only happen the first time it is a player's turn to bid on a concession.

17 Majors
* [ ] Charted corporations start with full capitalization (10 x share price) and five shares in the IPO. IPO shares do not pay revenue to the corporation, and may be purchased at par price.
* [ ] Non-chartered corporations start with half capitalization (5 x share price) and five shares in the IPO. IPO shares pay revenue to the treasury. They are purchased at market price and fund the corporation when purchased.
* [ ] A non-chartered corporation's par price is used only for refinancing and not for share purchases.
* [ ] When the president's certificate is purchased the president chooses whether it will be chartered or non-chartered and names the par price
* [ ] The corporation's home token is placed immediately on purchase of the president's certificate
* [ ] Maximum par price of non-charted corporations determined by the total number of corporations floated throughout the game
* [ ] Major corporations float when 50% is held by players, and receive their appropriate capitalization
* [ ] President may reserve a share at floatation if it is parred at 60f or higher
* [ ] If it is the first SR,  two or three shares may be reserved total, as marked on the Stock Market, for a stock price of 70 and 80 respectively.
* [ ] All major corporations are required to purchase four station tokens (including the home station already placed) for 100f. At the end of the SR, the president may buy additional tokens for the company for 25f, from its own funds, up to a maximum of 12. This decision is made in reverse operating order.

20 Options & Resolution
* [ ] Half-share options can be created during mergers and acquisitions, and during refinancing
* [ ] Meta to-do: study this section and add items here to reflect differences to 1862

21 Mergers & Acquisitions
* [ ] Mergers at start of operation
* [ ] Acquisitons at end of operation
* [ ] A merger can only happen if the two companies can trace an unblocked path to each other’s tokens by existing track on the board
* [ ] Meta to-do: study this section and add items here to reflect differences to 1862

22+
* [ ] Meta to-do: Add items from later sections of the rulebook

**Comment by tobymao** [comment]
closing for now
