### ISSUE TITLE
[1861] Variant implementation meta-issue

### ISSUE THREAD

**Issue by ollybh** [tobymao/18xx#8962]
There are several official variants for 1861, most of which have not yet been implemented.

## Train roster variants.
There are three variants as the the types and number of trains that become available after the first 8-train is bought:
- [ ] Two 5+5E trains and no 2+2 trains.
- [ ] Two 5+5E trains and two 2+2 trains.
- [x] Unlimited 5+5E trains and unlimited 2+2 trains.

The first of these is the default according to the rules in the first (JKLM) and second (AAG) editions. But everyone plays with unlimited 5+5E and 2+2 trains and it is the recommended way to play the game, according to its designer.

## National railway.
- [ ] The RSR does not have a treasury or loans, and exports a train at the end of each set of operating rounds.
- [ ] The RSR behaves like the CNR in 1867, exporting a train at the end of each operating round.

## Game end variants.
- [ ] Play until the bank breaks. This tends to lengthen the game by one or two operating rounds.
- [ ] When an 8-train is bought, finish the current OR set, have a SR and then a final set of three ORs. This is the same as 1867.
- [ ] The game end is triggered by the purchase of the first 6-train. Finish the current OR and then play two more ORs, with a SR in the usual sequence.

## Other 1867 rules.
- [x] 2D stock market instead of 3D.
- [ ] Grey track is available from the start of phase 7, not phase 6.
- [ ] When starting a public company by buying its director's share, you can start in any open city slot if there are no unconnected cities.
- [ ] Trains may be upgraded in phase 8.

## Auction variants.
- [ ] After a private or minor has been auctioned, the next player to act is the one to the left of the proposer, not the winner of the previous auction.
- [ ] Instead of auctioning individual private companies and minors at the start of the game, bundles of privates and minors are auctioned, with each player purchasing one bundle.

##  Miscellaneous variants.
- [ ] The RSR starts with a token in St Petersburg, in the city connected to the SE exit.
- [ ] A minor's stock price can fall below 35R when it is nationalised.

**Comment by ianwilson156** [comment]
I think that implementing all of these would be unnecessary, over-complicated, and possibly confusing for new players.

Two variants I would especially like to see are:
RSR exporting a train at the end of a set of rounds
Game end triggered by purchase of the first 6T

A variant which would be popular is allowing train upgrades in phase 8. 

There are two variants which are not 'official':
RSR exports a train each round
Game end like 1867

**Comment by ollybh** [comment]
@ianwilson156 wrote:
> There are two variants which are not 'official':
> RSR exports a train each round
> Game end like 1867

These are both taken from version 1.0 of the AAG 1867 rules, those are both marked as ones that you can use with 1861.

**Comment by ianwilson156** [comment]
"These are both taken from version 1.0 of the AAG 1867 rules, those are both marked as ones that you can use with 1861."

Ah yes, in the 'expansion' version of 1867 (rather than the 'full game' version). It does say, however, that these two variants must be used together.
[The reason being that the game might end too soon i.e. in OR5]

**Comment by philcampeau** [comment]
@ianwilson156 When it comes to this variant: 

> The end of the game is triggered by the purchase of the first 6-train. Finish the Operating Round, and play two more Operating Rounds, with a Stock Round in the usual sequence.

Does "the usual sequence" mean if you're in the first OR of the set, you finish that OR, play the second OR, have a Stock Round, and then play one final OR, or does it mean you finish the first OR of the set, have a Stock Round, and then do a 2-OR set?

**Comment by ianwilson156** [comment]
"Does "the usual sequence" mean if you're in the first OR of the set, you finish that OR, play the second OR, have a Stock Round, and then play one final OR, or does it mean you finish the first OR of the set, have a Stock Round, and then do a 2-OR set?"
The first of those options.
