### ISSUE TITLE
1822CA checklist

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#9376]
### Alpha blockers (last updated November 30)

- [x] GNWR and NTR destn hexes are explicit city slots. GNWR is the north edge slot, NTR is the SE
- [x] ~[game 13, WRS] autopass was pressed in SR3 for a player during the auction, but the auction came back around and the player as not autopassed.~ A Major was started, so this is actually WAI
- [x] [game 16, ERS] trying to lay tile Q1 in Quebec in OR3.1. getting an "undefined method. exchange token for nil" error. it was finicky. had to place the QMOO home token in the same location reserved for M5, and then was able to place the Q1 tile
    - if QMOO's home is different from M5's, maybe it needs to become a pending token again when a yellow tile is laid instead of it automatically going to one of the new cities
- [ ] [game 17, WRS] SR6 - $0 bids on privates disappearing
- [x] [game 17, WRS] OR 7.1 - GNWR incorrectly prompted about choosing home (related to 18's home being different in WRS than in full game)
- [x] [game 18, full game] OR 8.2 - ICR upgrades Montreal to gray (but only when paying for it instead of using P16) and then appears to have no `available_hexes` for running routes (ie all hexes are dimmed and not selectable)
- [x] [game 19, full game] P21 3-Tile Grant "The National Dream" should be able to lay tiles on Y cities
- [x] [game 21, ERS] infinite recursion error while computing sawmill bonus

-----

I skimmed the 1822CA rulebook and made this checklist mainly from the rules differences section highlighted in red. It looks like just the basic scaffolding/setup is implemented so far.

Terms defined differently in 1822CA rulebook vs 18xx.games code, such as "city", will use the 18xx.games code definition here.

* [1822CA Rulebook on BGG](https://boardgamegeek.com/filepage/238950/1822ca-rules)
* [Errata](https://docs.google.com/document/d/1puHQJV4eLeunOtu_RyqAT-_mBCI93u8dqSBNwWMsAiE/edit)

I'm thinking I'll start by getting the Eastern Regional Scenario playable first, then the Western scenario, and then the full game.

Any changes that are checked here but aren't merged in are pushed to a branch at https://github.com/michaeljb/18xx.games/branches.

### New/Changed Private Companies

Other privates equivalent to privates implemented for 1822, some work may still be needed to "wire" them up correctly.

ERS

- [x] P5-P6 Pullman (train becomes N+2N instead of N+inf)
- [x] P11 Tax Haven (can buy shares; should also add this as optional rule to 1822)
- [x] P13 Sawmill Bonus
- [x] P14-P18 Free <City> Upgrades
- [x] P25 Small Mail Contract

WRS

- [x] P19-P20 Yellowhead/Crowsnest Pass
- [x] P26-P27 Grain Trains

Full Game Only

- [x] P10 Winnipeg Station - teleport, add one slot to one city
- [x] P21 3-Tile Grant

### Toronto and M13

- [x] M13 must pay $20 to place its home station; this counts as its track laying step; it adds a slot to the city it chooses
- [x] after M13 is acquired, if the token is not used by the Major, the slot opens up for other Majors to use
- [x] acquiring M13 from the bid box costs an additional $20 for the token

### Operating Rounds

Tokens

- [x] may have a token on each different city on the same hex, but if the cities merge when upgraded, one returns to "available" section on the charter

Destination Tokens

- [x] GNW and NTR must reach specific city, not just the hex, to destinate
- [x] ICR does not need to reach a specific city in Quebec to destinate, but when it does, it must place its destination token in a city it does reach

Routes

- [x] no hitting different cities on one hex with a train, but may trace the route that way for connectivity
- [x] Duluth-Detroit is closed until phase 3 (full game only)
- [x] pullman/grain/port bonuses (WRS + full game)

Acquisitions

- [x] when a Major acquires a Minor, it gets a bonus yellow tile lay or upgrade; still may not lay on the same hex twice in one turn; cannot use a private company ability here

### Game End

- [x] if the bank breaks during an OR, finish the set and play an additional OR. Finish these ORs even if the game end value on the stock market is reached

### Eastern and Western Regional Scenarios

- [x] different private/minor/major selections for each scenario
    - [x] WRS: new homes for M16-M19
    - [x] WRS: no fixed first minor
- [x] special hexes for T10-T16
- [x] no Duluth-Detroit link
- [x] Game End conditions:
    - [x] stock market end during OR => end of OR
    - [x] stock market end from sold out during SR => end of OR X.1
    - [x] bank breaks during SR => end of OR X.1
    - [x] bank breaks during OR => end of OR X.2 (no extra OR); finish these even if stock market end is reached
- [x] 2p rules at https://boardgamegeek.com/thread/2591186/1822ca-2-player-scenarios
    - [x] different private companies
    - [x] price drops only on director sales

## Display Issues

- [x] stock market movement shown on Market tab
    - [x] selling shares should reflect the code value of `SELL_MOVEMENT = :left_per_10_if_pres_else_left_one` instead of saying down for every share
    - [x] sold out should be right instead of up

#### Tile Rendering

- [ ] Duluth (P18) - name/revenue strip clash
- [ ] Ottawa (AE15) - name clashing with upgrade cost
- [ ] Vancouver (C15) - destinations and port icon are obscured by revenue strip
- [x] Winnipeg (N16) - destination clashing with home reservation

## Other

- [x] P29/30 Remove Town privates should not be able to remove the P13 Sawmill town
- [x] combo_entities for private abilities which can be used together
- [x] Probable Sawmill bugs
    - [x] only one train per turn should get bonus
    - [x] bonus should be doubled by destination and E-trains
- [x] QMOO's home should be initially tied to the hex, not a specific city
- [x] Advanced Tile Lay is not working right now
- [x] abilities that require full tile action are still visible after doing some normal tile lays
- [x] Windsor-Detroit connection (2 lanes to 1) is not working properly
- [x] If a destination token and regular token are on the same hex and join up, ensure the regular token is the one sent back to the charter

## feedback from Bob

- [x] no currency symbol for upgrades on map
- [ ] show revenue icon for all cities on "big city" tiles
- [ ] fix labels overlapping with other tile parts, especially on W

#### game 12 - ERS
- [x] should probably have a note on the INFO page to describe the cost of the L upgrade
- [x] trying to place M12's home station into the GT location, game throws an error message "undefined method for neighbors for nil". same for M12's home location. (even if toronto tile is upgraded first, it still throws the error)

#### game 13 - WRS

- [x] M18 only lists the starting city as R16, needs name, also M19 M16
- [x] Prince Albert is M23's home, not Regina. (it has the 23 off to the side in the Regina hex)

- [x] NTR and M19 in play. NTR goes to play a tile and it throws an error. "undefined method include for Nil"
- [x] P26 text has the phrase "route route"

#### game 16 - ERS

 
- [x] M19 is permitted to upgrade Montreal to brown. it should not be permitted
- [x] GWR trying to use bonus tile upgrade on Hamilton to grey. merged in minor 16. it was not allowed
- [x] Privates that upgrade the major cities MOQTW still show the ability as active even when the associated tile is already maxed out at grey. in this case Quebec

#### game 18

- [x] OR9.1 - CNoR wanted to put the sawmill bonus into Kamloops. but when it did it was prevented from running a route through to Vancouver. removing the token and the route was valid. having the token it was not. i tried a few combinations, but anytime that token was on kamloops i was unable to select that city to include in a route, not even as a terminus

**Comment by scottredracecar** [comment]
Michael, nice to see you pick this up. Bob will be happy to see that.

**Comment by JEBrosius** [comment]
The grain elevator locations also have effects when run by non-grain trains.  See the table in Rule 5.11.27 and in particular the column for Normal Trains.

**Comment by scottredracecar** [comment]
For this one, I believe 1822MX had to solve this already.
`may have a token on each different city on the same hex, but if the cities merge when upgraded, one returns to "available" section on the charter`

**Comment by michaeljb** [comment]
> For this one, I believe 1822MX had to solve this already.
> > may have a token on each different city on the same hex, but if the cities merge when upgraded, one returns to "available" section on the charter

Sadly no... #9494

**Comment by WayneWWms** [comment]
Thank you so much for developing this game.  Don't have a copy but played it at Trax and really want to play it more.  So thanks.

**Comment by tobymao** [comment]
@WayneWWms glad you're excited for. if you find yourself enjoying the game, please consider supporting the publisher and purchasing a physical copy!

**Comment by Kroomiester** [comment]
Is this game ready for alpha? I am very ignorant when it comes to programming things, but would it be playable without the last few tile rendering tasks complete? If not please correct me, I mean no offence and I appreciate everything this community has built on this site, just very excited to play 1822CA

**Comment by michaeljb** [comment]
Bob (Robert Lecuyer, the 1822CA designer) wanted to do some pre-alpha testing and hammer out some more bugs before we go live. He's already found a few things that went wrong which I thought I would get "for free" from the 1822 implementation or I just didn't test enough on my first try.

It is close to alpha, but it's hard to say exactly when we'll make it alpha.

**Comment by michaeljb** [comment]
> [game 13, WRS] autopass was pressed in SR3 for a player during the auction, but the auction came back around and the player as not autopassed.

 CNoR was started and that disabled the autopass, so this part is actually WAI
