### ISSUE TITLE
1822Africa Checklist

### ISSUE THREAD

**Issue by vandamm** [tobymao/18xx#9419]
The game is being implemented based on these documents:
- [Map](https://boardgamegeek.com/image/7682366/scottredracecar)
- [Rules differences from 1822](https://docs.google.com/document/d/1tgRiGEqSKZSQrJ92Wq-rbb0kS2xBZAr0hao3RMjKqcI/edit)
- [Private companies](https://docs.google.com/spreadsheets/d/1yX8NeNFsgTf7dLbzZ69ZnESZvaWC_3MlGyvqZKPDEtI/edit?usp=sharing)
- [Phases](https://github.com/tobymao/18xx/pull/9414#issuecomment-1681402941)

#### From 1822
- [x] P1 - Permanent L-train
- [x] P2, P3 - Permanent 2-train
- [x] P9 - Remove Town
- [x] P13 - Station Swap
- [x] P16 - A10x Phase

#### From 1822MX
- [x] P4, P5 - Pullman
- [x] P7 - Extra tile

#### Unique
Most of these privates require a lot of work so they will be implemented after everything else
- [x] P6 - Recycled train
- [x] P8 - Reserve Three Tiles
- [x] P10 - Game Reserve
- [x] P11 - Mountain Rebate
- [x] P12 - Fast Sahara Building
- [x] P14 - Gold Mine
- [x] P15 - Coffee Plantation
- [x] P17 - Bank Share Buy
- [x] P18 - Safari Bonus

## Map
- [x] Custom major company logos
- [x] Game reserves - Special map hex/tile that does not count against the train number (can’t be run with E).

## Stock market
- [x] Minor companies may not advance beyond 90 value. 
- [x] If they would otherwise move right, they remain in the same space and retain their position in the stack.

## Stock round
- [x] Single queue with only three bid boxes
- [x] There are two back-to-back  stock rounds each time there would normally be an 1822 stock round.
- [x] Before each of the first two SRs, find the top-most concession and place all cards before it at the bottom of the deck (preserving the order)
- [x] SR End: Clear bid box cards and export trains at the end of each round like in 1822.
- [x] SR End: Additionally, if there is a concession in bid box 1, clear it (but don’t remove a train). This major is no longer available to start from a concession.
- [x] SR End: If no cards were bought from the bid boxes during the SR, remove each of the cards in the bid boxes from the game before restocking (but after train exporting, if any).

## Operating Round
- [x] 5/E and 6/E trains are single sided and run as either a N-train or E-train (president chooses each run).
- [x] Acquisitions may happen during the first OR a company operates (minor or major or both).

## Game End
- [x] After OR set after cards can no longer refill the bid boxes after an SR

## Current issues
- [x] Special trains are displayed in "Upcoming Trains" box
- [x] Operation round names don't show the number of OR in the set
- [ ] Spreadsheet tab shows SR numbers as SR1 instead of SR1.1
- [x] #9550
- [x] P16 doesn't close in Phase 6
