### ISSUE TITLE
[1844] Implementation Checklist

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#9553]
Setup
- [x] Currency format - ddd SFR
- [x] Bank - 1200 SFR
- [x] Starting cash -  3: 800 SFR, 4: 620 SFR, 5: 510 SFR, 6: 440 SFR, 7: 400 SFR
- [x] Certificate limit - 3: 24 4: 18 5: 15 6: 13 7: 11
- [x] Meta
- [x] Map
  - [x] Show future tile upgrades
  - [x] EW bonuses
  - [x] D15 upgrades to a green city. It is not an OO hex.
  - [x] Milan is the same offboard to the west
  - [x] Do mountain railways need impassible boarders for track lay logic?
- [x] Tiles
- [x] Corporation logos and colors

Private Companies
- [x] Sold for 1 SFR to 2x value
- [x] Cannot be purchased by Pre-SBB corporations
- [x] P1 - Brienzer-Rothorn-Bahn
  - [x] Value - 20 SFR, Revenue 5 SFR
- [x] P2 - Bödelibahn
  - [x] Value - 40 SFR, Revenue 10 SFR
  - [x] Once in the game, a company may place an additional yellow track tile according to the rules. Either that company or its director must be the owner of the P2. Turn over the certificate after use.
  - [x] Cannot be used until Phase 3
- [x] P3 - Gotthard-Postkutsche
  - [x] Value - 80 SFR, Revenue 15 SFR
  - [x] Comes with a Tunnel certificate
- [x]  P4 - Furka-Oberalbahn
  - [x] Value - 110 SFR, Revenue 20 SFR
  - [x] The owner of this Private Railway company may at any time place the Furka-Oberalp
special tile. This is an additional tile lay and free of cost. Doing this closes the P4; its owner receives 80 SFR as a compensation. This happens at the latest by the sale of the first 5/5H train (begin of Phase 5). Its owner can’t waive that build.
![image](https://github.com/tobymao/18xx/assets/67359577/d13b6e4e-5395-49e0-b2a3-b5e55b9d8ed0)
  - [x] Cannot be used until Phase 3
- [x] P5 - Compagnie Montreaux-Montbovon
  - [x] Value - 140 SFR, Revenue 25 SFR
  - [x] Comes with a 10% share of the MOB. This share can’t be sold unless the director’s share of the MOB was bought and hence an issue price determined.
- [x] P6 - Societa Anonima Delle Ferrovie
  - [x] Value - 180 SFR, Revenue 30 SFR
  - [x] Cannot be bought by a corporation
  - [x] Comes with the director’s share of the FNM. The P6 owner sets the issue price for the NM. The P6 will be closed as soon as the FNM runs a train on a route for the first time. (As three shares of the FNM are placed in the bank pool during setup, the FNM will operate immediately.)
- [x] P7 - Lokfabrik Oerlikon
  - [x] Value - 100 SFR
  - [x] Cannot be bought by a corporation
  - [x] The P7 will be closed as soon a 5 or 5H train is bought. The owner of the P67 gets the 5H train named “EVA”. He may give it immediately or later to any company he’s the director of. Train limits have to be kept.

Corporations
- [x] Large Historical (H1 - H6)
  - [x] The corporations
    - [x] H1 Ferrovie Nord Milano (FNM), home base Como, destination hex Altdorf
    - [x] H2 Rhätische Bahn (RhB), home base Chur, destination hex Brig
    - [x] H3 Bern - Lötschberg – Simplon (BLS), home base Bern, destination hex Brig
    - [x] H4 Sensetalbahn (STB), home base Aarau, destination hex Thun
    - [x] H5 Appenzeller Bahn (AB), home base Appenzell, destination hex Winterthur or Frauenfeld
    - [x] H6 Montreux - Oberland bernois (MOB), home base Montreux, destination hex Thun
  - [x] Par price determines number of stations (60: 1, 70: 2, 80: 3, 90: 4, 100 5)
  - [x] Can run any type of train
  - [x] 10% shares
  - [x] Floats at 50% (5x capitalization)
  - [x] Receives remaining capitalization upon reaching their destination
  - [x] Full capitalization at Phase 6, no destination
- [x] Pre-SBB (V1 - V5)
  - [x] The corporations
    - [x]  V1 Schweizerische Nordostbahn (NOB), home base Zürich, destination hex Aarau
    - [x]  V2 Schweizerische Centralbahn (SCB), home base Basel, destination hex Lucerne
    - [x]  V3 Vereinigte Schweizer Bahnen (VSB), home base St. Gallen, destination hex Sargans
    - [x]  V4 Jura – Simplon (JS), home base Lausanne, destination hex Neuchatel
    - [x]  V5 Gotthardbahn (GB), home base Stans, destinates when Gotthard tunnel built
  - [x]  2 stations (Free, 40)
  - [x] 25% shares
  - [x] Floats at 50% capitalization (2x capitalization)
  - [x] Receives remaining capitalization upon reaching their destinations.
  - [x] Train limit of 2
  - [x] Not required to own a train (no EMR)
  - [x] Can run any train type
  - [x] Merges into SBB
  - [x] If not formed before SBB, their home base is not reserved for the SBB
- [x] Regional (R1 - R3)
  - [x] The corporations
    - [x] R1 Jura neuchatelois (JN), home base Neuchatel
    - [x] R2 Chur – Arosa (ChA), home base Arosa
    - [x] R3 Visp – Zermatt (VZ), home base Sion
  - [x] 20% shares
  - [x] Float at 50% (3 shares) and receive 5x capitalization (full - no destination)
  - [x] Max stock price is limited to 200 (moves up when hits the red line)
  - [x] Can only own H-trains
  - [x] Required to own a train with a valid route (ignore red off-boards or unplaced mountain railways)

Railway Companies
- [x] Mountain Railways (B1 - B5)
  - [x] Cost 150 SFR
  - [x] Place revenue marker immediately upon purchase (3 options, limited to 2 of each type)
  - [x] Receives 40 SFR income each OR once a corporation has run to the mountain
  - [x] End game value is 150 SFR if a corporation has run to the mountain
  - [x] Does not count towards the cert limit
- [x] Tunnel Companies
  - [x] Cost 50 SFR
  - [x] Can be used by one of owner's corporations to build a tunnel
  - [x] Receives 10 SFR income each OR once a corporation has run to the mountain
  - [x] End game value is 50 SFR if a corporation has run to the mountain
  - [x] Does not count towards the cert limit

Trains
<img width="517" alt="image" src="https://github.com/tobymao/18xx/assets/67359577/3032929d-88ce-4cdf-869a-b24ac34afa5a">
- [x] H-trains include starting hex and cannot run offboards
- [x] E-trains can skip cities, but must count at least one company tokened city
- [x] Regular trains are downgraded to H-trains by phase

ISR
- [x] Same auction style as 1880
- [x] If no one bids on P1, reduce the price by 5 SFR. Player 1 has to take it for 0 SFR.
- [x] Afterwards, if all pass, pay dividends and reenter the ISR
- [x] Turn order after ISR is least cash to most

Stock Round
- [x] Sell than buy
- [x] Selling
  - [x] If the corporation has not yet operated, move stock price down and receive new market value
  - [x] No sales in SR1
  - [x] No more than 50% of the corporation's shares may be in the bank pool
- [x] Buying
  - [x] Shares purchased at par value
  - [x] Each player can only buy one mountain railway and one tunnel company during the SR
  - [x] Can buy 1 more than half the shares of a corporation from the IPO. No limit from the market.
  - [x] Privates, mountain railways, and tunnel companies do not count against the cert limit.
- [x] End of SR
  - [x] Priority by most cash
  - [x] Corporations with shares in the bank pool move left
  - [x] Sold out move up (bounce if at top)

Operating Round
- [x] Track
  - [x] Building a tunnel is an extra action (owning player must also own a tunnel company). Only one tunnel can be built on each tunnel hex (from and to tunnel mouth). Gentle curve or straight track. Costs 100 SFR from the corporation. Multiple tunnel companies can be used in the same turn.
- [x] Destinations
  - [x] Connected by infinite train (cannot go through blocked cities)
  - [x] Triggered for all corporations on any corporation's turn. This can happen in the middle of tile laying.
- [x] Stations
  - [x] First station 40 SFR and each other is 100 SFR
  - [x] One station per hex for a corporation
- [x] Run trains
  - [x] Route cannot include the same mountain railway more than once
  - [x] EW and NS bonuses
  - [x] +10 per stop if run through a tunnel
- [x] Dividends
  - [x] Pay or withhold. 
  - [x] If total shareholder holdings is not a multiple of 10, total payout is rounded up to the nearest SFR. Rounded down for bank shares paying the corporation.
- [x] Train buying
  - [x] Can buy either regular or H train variant
  - [x] Can buy trains from other companies after first 3/3H purchased
  - [x] Buying a train from another director must be done at the train's face value 
- [x] EMR
  - [x] No change of director may occur from sale of shares (including other corporations)
  - [x] Not required to sell shares (optional)
  - [x] Can take loan like in 1880 (50% interest immediately and at end of each SR). No bankruptcy.
  - [x] Director can buy from bank, market, or other companies (cannot be greater than face value of train)
- [x] Exporting
  - [x] Next train exports

Phases
- [ ]![image](https://github.com/tobymao/18xx/assets/67359577/c5cd5f82-25da-42dd-a619-430f1dba65f0)

SBB
- [x] Forms at end of OR after first 5/5H sold/exported
- [x] Starting price is on the 6th row down of the share chart at 100 SFR
- [x] Comes with untradeable 5H that is not part of the train count.
- [x] Gets all Pre-SBB tokens (if two on the same hex, goes back to charter)
- [x] Select which token to remove when two tokens in different cities on the same hex
- [x] SBB president shares exchange for 10% shares and other shares for 5% shares (gain or lose the difference in share price). Automatically take a loan if cannot pay, which is not subject to the 50% debt tax.
- [x] Unsold shares go into the bank pool
- [x] In case of share tie, the player that was president of the lower numbered Pre-SBB company wins the tiebreaker
- [x] Upon director change, must exchange with a 10% certificate if possible
- [x] Must buy and sell trains at face value
- [x] 4 train limit

Game End
- [x] Bank runs out of money
- [x] Play until end of OR set
- [x] Subtract any remaining debt from final score

**Comment by BellmakerSA** [comment]
Fwiw the Lookout version is very bad about indicating this (it’s only on the SBB charter) but the SBB can only buy/sell trains at face value (like the NdM in 18MEX)

**Comment by crericha** [comment]
> Fwiw the Lookout version is very bad about indicating this (it’s only on the SBB charter) but the SBB can only buy/sell trains at face value (like the NdM in 18MEX)

Thanks, @BellmakerSA! I added that to the checklist. If you see anything incorrect or missing in the checklist, please let me know.

**Comment by BellmakerSA** [comment]
> > Fwiw the Lookout version is very bad about indicating this (it’s only on the SBB charter) but the SBB can only buy/sell trains at face value (like the NdM in 18MEX)
> 
> Thanks, @BellmakerSA! I added that to the checklist. If you see anything incorrect or missing in the checklist, please let me know.

I don’t think you’ll be able to enforce this but companies must run for the highest run they can (they can’t run for less to activate a tunnel or mountain’s income).

**Comment by philcampeau** [comment]
> Pre-SBB (V1 - V5)
>  - [ ] 2 stations?
>  - [ ] Floats at 50% capitalization (5x capitalization)

 
 Yes, 2 stations. Note, they float at 50% with **2x capitalisation**.

> Buying
>  - [ ] Shares purchased at par value
>  - [ ] Each player can only buy one mountain railway and one tunnel company during the SR
>  - [ ]  60% ownership limit

Note that you can buy up to 100% from the market. Also, the ownership limit for pre-SBB from IPO is 75% rather than 60%.

> SBB
>  - [ ] Comes with untradeable 5H (I believe this is not part of the train count -- need to confirm)

Correct, not part of the train count.

**Comment by crericha** [comment]
> > Pre-SBB (V1 - V5)
> > 
> > * [ ]  2 stations?
> > * [ ]  Floats at 50% capitalization (5x capitalization)
> 
> Yes, 2 stations. Note, they float at 50% with **2x capitalisation**.
> 

The rulebook says 5x. Is that a typo?

> > Buying
> > 
> > * [ ]  Shares purchased at par value
> > * [ ]  Each player can only buy one mountain railway and one tunnel company during the SR
> > * [ ]   60% ownership limit
> 
> Note that you can buy up to 100% from the market. Also, the ownership limit for pre-SBB from IPO is 75% rather than 60%.
> 

Updated to can buy 1 more than half the shares from the IPO. No limit from the market.

> > SBB
> > 
> > * [ ]  Comes with untradeable 5H (I believe this is not part of the train count -- need to confirm)
> 
> Correct, not part of the train count.

Updated

**Comment by crericha** [comment]
Updated from errata, including the pre-sbb getting 2x capital.

**Comment by philcampeau** [comment]
Another detail, Pre-SBB corps can't buy in privates. Regional and Historic corps can.

**Comment by crericha** [comment]
Complete
